/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import Code.DBconnect;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class account extends javax.swing.JInternalFrame {

    Connection con=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int hour,second,minute;
    int day,month,year;
    String timestr,yearstr;
    /**
     * Creates new form account
     */
    public account() {
        initComponents();
        con = DBconnect.connect();
        setDateTime();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        accnobox = new javax.swing.JLabel();
        namebox = new javax.swing.JLabel();
        deamountbox = new javax.swing.JTextField();
        findbtn = new javax.swing.JButton();
        acctypebox = new javax.swing.JLabel();
        clearbtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        datebox = new javax.swing.JLabel();
        timebox = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Accounts");

        jPanel3.setBackground(new java.awt.Color(167, 206, 243));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ID");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(40, 20, 30, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Account No");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(40, 60, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Full Name");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 100, 80, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Account Type");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(40, 140, 100, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Deposit Amount");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(40, 180, 110, 15);

        idbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        idbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idboxKeyPressed(evt);
            }
        });
        jPanel3.add(idbox);
        idbox.setBounds(170, 10, 160, 30);

        accnobox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        accnobox.setText("Acc No");
        jPanel3.add(accnobox);
        accnobox.setBounds(170, 60, 60, 14);

        namebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        namebox.setText("Name");
        jPanel3.add(namebox);
        namebox.setBounds(170, 100, 150, 14);

        deamountbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deamountbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deamountboxKeyPressed(evt);
            }
        });
        jPanel3.add(deamountbox);
        deamountbox.setBounds(170, 170, 160, 30);

        findbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        findbtn.setText("Find");
        findbtn.setAlignmentY(1.0F);
        findbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        findbtn.setIconTextGap(6);
        findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbtnActionPerformed(evt);
            }
        });
        jPanel3.add(findbtn);
        findbtn.setBounds(340, 10, 80, 30);

        acctypebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        acctypebox.setText("Acc Type");
        jPanel3.add(acctypebox);
        acctypebox.setBounds(170, 140, 100, 14);

        clearbtn.setBackground(new java.awt.Color(204, 204, 204));
        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clean.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        addbtn.setBackground(new java.awt.Color(204, 204, 204));
        addbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insert-.png"))); // NOI18N
        addbtn.setText("ADD");
        addbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        datebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        datebox.setText("Date");

        timebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        timebox.setText("Time");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sanasa2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(147, 147, 147)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(datebox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timebox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datebox)
                    .addComponent(timebox))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idboxKeyPressed
        String phone =idbox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<3){
                idbox.setEditable(true);
            }else{
                idbox.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                idbox.setEditable(true);
            }else{
                idbox.setEditable(false);
            }
        }
    }//GEN-LAST:event_idboxKeyPressed

    private void deamountboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deamountboxKeyPressed
        String phone =deamountbox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                deamountbox.setEditable(true);
            }else{
                deamountbox.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                deamountbox.setEditable(true);
            }else{
                deamountbox.setEditable(false);
            }
        }
    }//GEN-LAST:event_deamountboxKeyPressed

    private void findbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbtnActionPerformed

        if(idbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please type ID","Information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            int   id=Integer.parseInt(idbox.getText());
            try {

                if(id>=1 && id<=500){
                    pst = con.prepareStatement("SElECT memberid,fname,lname FROM member WHERE memberid=?");
                    int search = Integer.parseInt(idbox.getText());
                    pst.setInt(1, search);
                    rs = pst.executeQuery();
                    if(rs.next()==true){
                        String memid = rs.getString("memberid");
                        String fname =  rs.getString("fname");
                        String lname =  rs.getString("lname");
                        accnobox.setText(memid);
                        namebox.setText(fname+" "+lname);
                        acctypebox.setText("Member");
                    }else{
                        JOptionPane.showMessageDialog(null, "Search item not found","Information",JOptionPane.INFORMATION_MESSAGE);
                    }
                }else{
                    if(id>=501 && id<=700){
                        pst = con.prepareStatement("SElECT childid,fname,lname FROM child WHERE childid='"+id+"'");
                        rs = pst.executeQuery();
                        if(rs.next()==true){
                            String childid = rs.getString("childid");
                            String fname =  rs.getString("fname");
                            String lname =  rs.getString("lname");
                            accnobox.setText(childid);
                            namebox.setText(fname+" "+lname);
                            acctypebox.setText("Child");
                        }else{
                            JOptionPane.showMessageDialog(null, "Search item not found","Information",JOptionPane.INFORMATION_MESSAGE);
                        }
                    }else{
                        pst = con.prepareStatement("SElECT nonmemid,fname,lname FROM nonmember WHERE nonmemid='"+id+"'");
                        rs = pst.executeQuery();
                        if(rs.next()==true){
                            String nonmemid = rs.getString("nonmemid");
                            String fname =  rs.getString("fname");
                            String lname =  rs.getString("lname");
                            accnobox.setText(nonmemid);
                            namebox.setText(fname+" "+lname);
                            acctypebox.setText("Non-Member");
                        }else{
                            JOptionPane.showMessageDialog(null, "Search item not found","Information",JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_findbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clear();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addbtnMouseClicked

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed

        String accno = accnobox.getText();
        String name = namebox.getText();
        String acctype = acctypebox.getText();
        String date = datebox.getText();
        String time = timebox.getText();

        if( accno.equals("Acc No")  || deamountbox.getText().isEmpty() || idbox.getText().isEmpty() || name.equals("Name")  ||  acctype.equals("Acc Type")){
            JOptionPane.showMessageDialog(null, "Some fields are Empty");
        }else{

            int damount = Integer.parseInt(deamountbox.getText());
            int   id=Integer.parseInt(idbox.getText());
            if(damount>=500){
                try {
                    pst = con.prepareStatement("SElECT accno FROM memberacc WHERE accno=?");
                    int search = Integer.parseInt(idbox.getText());
                    pst.setInt(1, search);
                    rs = pst.executeQuery();

                    if (rs.next()==true){
                        JOptionPane.showMessageDialog(null, "An account has already been opened");
                    } else{
                        pst = con.prepareStatement("SElECT accno FROM childacc WHERE accno=?");
                        int srch = Integer.parseInt(idbox.getText());
                        pst.setInt(1, srch);
                        rs = pst.executeQuery();

                        if (rs.next()==true){
                            JOptionPane.showMessageDialog(null, "An account has already been opened");
                        }else{
                            pst = con.prepareStatement("SElECT accno FROM nonmemberacc WHERE accno=?");
                            int sch = Integer.parseInt(idbox.getText());
                            pst.setInt(1, sch);
                            rs = pst.executeQuery();

                            if (rs.next()==true){
                                JOptionPane.showMessageDialog(null, "An account has already been opened");
                            }else{
                                if(id>=1 && id<=500){
                                    String sql = "INSERT INTO memberacc (accno,memberid,name,balance,date,time) VALUES ('"+accno+"','"+id+"','"+name+"', '"+damount+"','"+date+"','"+time+"')";
                                    pst = con.prepareStatement(sql);
                                    pst.execute();
                                    JOptionPane.showMessageDialog(null,"Added Succesfull");
                                }else{
                                    if(id>=501 && id<=700){
                                        String sql = "INSERT INTO childacc (accno,childid,name,balance,date,time) VALUES ('"+accno+"','"+id+"','"+name+"', '"+damount+"','"+date+"','"+time+"')";
                                        pst = con.prepareStatement(sql);
                                        pst.execute();
                                        JOptionPane.showMessageDialog(null,"Added Succesfull");
                                    }else{
                                        String sql = "INSERT INTO nonmemberacc (accno,nonmemid,name,balance,date,time) VALUES ('"+accno+"','"+id+"','"+name+"', '"+damount+"','"+date+"','"+time+"')";
                                        pst = con.prepareStatement(sql);
                                        pst.execute();
                                        JOptionPane.showMessageDialog(null,"Added Succesfull");
                                    }
                                }
                            }
                        }
                    }
                } catch (Exception e) {
                }
                clear();
            }else{
                JOptionPane.showMessageDialog(null,"A deposit of more than Rs.500/= is required");
            }
        }

    }//GEN-LAST:event_addbtnActionPerformed

    public void clear(){
        accnobox.setText("Acc No");
        namebox.setText("Name");
        acctypebox.setText("Acc Type");
        idbox.setText("");
        deamountbox.setText("");
    }
    
    public void setDateTime() {
        
        Calendar c = Calendar.getInstance();
        hour= c.get(Calendar.HOUR_OF_DAY);
        if (hour >12)
            hour=hour -12;
        minute= c.get(Calendar.MINUTE);
        second= c.get(Calendar.SECOND);
        year= c.get(Calendar.YEAR);
        month= c.get(Calendar.MONTH);
        day= c.get(Calendar.DAY_OF_MONTH);
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date dat = c.getTime();
        timestr=sdf.format(dat);
        yearstr=df.format(dat);
        timebox.setText(timestr);
        datebox.setText(yearstr);
               

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accnobox;
    private javax.swing.JLabel acctypebox;
    private javax.swing.JButton addbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel datebox;
    private javax.swing.JTextField deamountbox;
    private javax.swing.JButton findbtn;
    private javax.swing.JTextField idbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel namebox;
    private javax.swing.JLabel timebox;
    // End of variables declaration//GEN-END:variables
}
