/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;
import Code.DBconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Base64;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class admin extends javax.swing.JInternalFrame {
    Connection con=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        con = DBconnect.connect();
    }
    
    public void clear(){
        usernamebox.setText("");
        pwdbox.setText("");
        repwdbox.setText("");
        namebox.setText("");
        cpwdbox.setText("");
        newpwdbox.setText("");
        cnewpwdbox.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernamebox = new javax.swing.JTextField();
        pwdbox = new javax.swing.JPasswordField();
        repwdbox = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        registerbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        newpwdbox = new javax.swing.JPasswordField();
        cnewpwdbox = new javax.swing.JPasswordField();
        findbtn = new javax.swing.JButton();
        cpwdbox = new javax.swing.JPasswordField();
        jPanel7 = new javax.swing.JPanel();
        okbtn = new javax.swing.JButton();
        clearbtn2 = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(650, 452));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(102, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("User Name");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(50, 30, 120, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Password");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(50, 80, 120, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Confirm Password");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(50, 130, 120, 15);

        usernamebox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(usernamebox);
        usernamebox.setBounds(190, 20, 150, 30);

        pwdbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwdbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(pwdbox);
        pwdbox.setBounds(190, 70, 150, 30);

        repwdbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        repwdbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        repwdbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                repwdboxKeyReleased(evt);
            }
        });
        jPanel4.add(repwdbox);
        repwdbox.setBounds(190, 120, 150, 30);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(null);

        registerbtn.setBackground(new java.awt.Color(204, 204, 204));
        registerbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registration.png"))); // NOI18N
        registerbtn.setText("Register");
        registerbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });
        jPanel5.add(registerbtn);
        registerbtn.setBounds(50, 30, 110, 40);

        clearbtn.setBackground(new java.awt.Color(204, 204, 204));
        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clean.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel5.add(clearbtn);
        clearbtn.setBounds(230, 30, 100, 40);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("New Admin Registration", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("User Name");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(40, 30, 150, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Current Password");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(40, 70, 150, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("New Password");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(40, 110, 150, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Confirm New Password");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(40, 150, 150, 15);

        namebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel6.add(namebox);
        namebox.setBounds(210, 20, 150, 30);
        jPanel6.add(newpwdbox);
        newpwdbox.setBounds(210, 100, 150, 30);

        cnewpwdbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnewpwdboxActionPerformed(evt);
            }
        });
        cnewpwdbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cnewpwdboxKeyReleased(evt);
            }
        });
        jPanel6.add(cnewpwdbox);
        cnewpwdbox.setBounds(210, 140, 150, 30);

        findbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        findbtn.setText("Find");
        findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbtnActionPerformed(evt);
            }
        });
        jPanel6.add(findbtn);
        findbtn.setBounds(370, 20, 80, 30);
        jPanel6.add(cpwdbox);
        cpwdbox.setBounds(210, 60, 150, 30);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setLayout(null);

        okbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        okbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ok.png"))); // NOI18N
        okbtn.setText("OK");
        okbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });
        jPanel7.add(okbtn);
        okbtn.setBounds(50, 30, 100, 40);

        clearbtn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearbtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clean.png"))); // NOI18N
        clearbtn2.setText("Clear");
        clearbtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtn2ActionPerformed(evt);
            }
        });
        jPanel7.add(clearbtn2);
        clearbtn2.setBounds(230, 30, 100, 40);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Change Password", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void repwdboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_repwdboxKeyReleased
        String   password = pwdbox.getText();
        String repwd = repwdbox.getText();

        if(password.equals(repwd)){
            repwdbox.setBackground(Color.GREEN);
            registerbtn.setEnabled(true);
        }else{
            if(repwd.isEmpty()){
                repwdbox.setBackground(Color.WHITE);
                registerbtn.setEnabled(false);
            }else{
                repwdbox.setBackground(Color.RED);
                registerbtn.setEnabled(false);
            }
        }
    }//GEN-LAST:event_repwdboxKeyReleased

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        if(usernamebox.getText().isEmpty() || pwdbox.getText().isEmpty() || repwdbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Some feild is Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }else{

            try {
                String   password = pwdbox.getText();
                String encrypted = encryptPassword(password);
                String name =usernamebox.getText();

                pst=con.prepareStatement("SELECT * FROM login WHERE username=?");
                pst.setString(1, name);
                rs = pst.executeQuery();
                if(rs.next()==false){
                    String sql = "INSERT INTO login (username,password) VALUES ('"+name+"','"+encrypted+"')";
                    pst = con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Registred Succesfull","Information",JOptionPane.INFORMATION_MESSAGE);
                    clear();
                }else{
                    JOptionPane.showMessageDialog(null, "Duplicate username", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_registerbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clear();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void cnewpwdboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnewpwdboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnewpwdboxActionPerformed

    private void cnewpwdboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnewpwdboxKeyReleased
        String   password = newpwdbox.getText();
        String repwd = cnewpwdbox.getText();

        if(password.equals(repwd)){
            cnewpwdbox.setBackground(Color.GREEN);
            okbtn.setEnabled(true);
        }else{
            if(repwd.isEmpty()){
                cnewpwdbox.setBackground(Color.WHITE);
                okbtn.setEnabled(false);
            }else{
                cnewpwdbox.setBackground(Color.RED);
                okbtn.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cnewpwdboxKeyReleased

    private void findbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbtnActionPerformed
        if(namebox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter current username", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                String txt = namebox.getText();
                pst=con.prepareStatement("SELECT * FROM login WHERE username=?");
                pst.setString(1, txt);
                rs = pst.executeQuery();
                if(rs.next()==false){
                    JOptionPane.showMessageDialog(null, "Search item not found", "Error", JOptionPane.ERROR_MESSAGE);
                }else{
                    String pwd = rs.getString("password");
                    String decrypted = decryptPassword(pwd);
                    cpwdbox.setText(decrypted);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_findbtnActionPerformed

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtnActionPerformed
        if(namebox.getText().isEmpty() || cpwdbox.getText().isEmpty() || newpwdbox.getText().isEmpty() ||cnewpwdbox.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Some feild is Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                String name =namebox.getText();
                String   password = newpwdbox.getText();
                String encrypted = encryptPassword(password);
                String sql = "UPDATE login SET password='"+encrypted+"' WHERE username= '"+name+"'";
                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null,"Password change succesfull");
                clear();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_okbtnActionPerformed

    private void clearbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtn2ActionPerformed
        clear();
    }//GEN-LAST:event_clearbtn2ActionPerformed

 public static String encryptPassword(String password) {
        return Base64.getEncoder().encodeToString(password.getBytes());
    }
  public static String decryptPassword(String encryptedPassword) {
        byte[] decodedBytes = Base64.getDecoder().decode(encryptedPassword);
        return new String(decodedBytes);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton clearbtn2;
    private javax.swing.JPasswordField cnewpwdbox;
    private javax.swing.JPasswordField cpwdbox;
    private javax.swing.JButton findbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField namebox;
    private javax.swing.JPasswordField newpwdbox;
    private javax.swing.JButton okbtn;
    private javax.swing.JPasswordField pwdbox;
    private javax.swing.JButton registerbtn;
    private javax.swing.JPasswordField repwdbox;
    private javax.swing.JTextField usernamebox;
    // End of variables declaration//GEN-END:variables
}
