/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;
import Code.DBconnect;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class adminchanges extends javax.swing.JInternalFrame {
    Connection con=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form adminchanges
     */
    public adminchanges() {
        initComponents();
        con = DBconnect.connect();
        setdata();
    }
    
    public void clear (){
       sharebox.setText(""); 
       llimitbox.setText("");
       mandatorybox.setText("");
       securitiesbox.setText("");
       frombox.setText("");
       tobox.setText("");
       interestbox.setText("");
       installcalbox.setText("");
    }
    
    public void setdata(){
        try {
           pst = con.prepareStatement("SElECT share,mandatory,securities,loan_limit,frominstallment,toinstallment,callimit,interest FROM admin ");
           rs = pst.executeQuery();
           rs.next();
           int limit = rs.getInt("loan_limit");
           int from = rs.getInt("frominstallment");
           int to = rs.getInt("toinstallment");
           int share = rs.getInt("share");
           int manda = rs.getInt("mandatory");
           int sec = rs.getInt("securities");
           int cal = rs.getInt("callimit");
           int interest = rs.getInt("interest");
           
            tobox.setText(String.valueOf(to));
            frombox.setText(String.valueOf(from));
            llimitbox.setText(String.valueOf(limit));
            sharebox.setText(String.valueOf(share));
            mandatorybox.setText(String.valueOf(manda));
            securitiesbox.setText(String.valueOf(sec));
            interestbox.setText(String.valueOf(interest));
            installcalbox.setText(String.valueOf(cal));
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        llimitbox = new javax.swing.JTextField();
        mandatorybox = new javax.swing.JTextField();
        securitiesbox = new javax.swing.JTextField();
        sharebox = new javax.swing.JTextField();
        frombox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tobox = new javax.swing.JTextField();
        interestbox = new javax.swing.JTextField();
        installcalbox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        okbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(562, 516));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Admin");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sanasa2.png"))); // NOI18N

        jPanel3.setBackground(java.awt.SystemColor.activeCaption);
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Loan Limit");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 30, 200, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mandatory Deposit  Presentage");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 70, 200, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Presentage of securities deposit");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 110, 200, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Minimum Share price");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 270, 200, 15);

        llimitbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        llimitbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                llimitboxKeyPressed(evt);
            }
        });
        jPanel3.add(llimitbox);
        llimitbox.setBounds(260, 20, 160, 30);

        mandatorybox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mandatorybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mandatoryboxActionPerformed(evt);
            }
        });
        mandatorybox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mandatoryboxKeyPressed(evt);
            }
        });
        jPanel3.add(mandatorybox);
        mandatorybox.setBounds(260, 60, 160, 30);

        securitiesbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        securitiesbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                securitiesboxKeyPressed(evt);
            }
        });
        jPanel3.add(securitiesbox);
        securitiesbox.setBounds(260, 100, 160, 30);

        sharebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sharebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                shareboxKeyPressed(evt);
            }
        });
        jPanel3.add(sharebox);
        sharebox.setBounds(260, 260, 160, 30);

        frombox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        frombox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fromboxKeyPressed(evt);
            }
        });
        jPanel3.add(frombox);
        frombox.setBounds(260, 140, 60, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Loan installment range");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 150, 150, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("From");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(220, 150, 40, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("To");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(330, 150, 20, 15);

        tobox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tobox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                toboxKeyPressed(evt);
            }
        });
        jPanel3.add(tobox);
        tobox.setBounds(360, 140, 60, 30);

        interestbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(interestbox);
        interestbox.setBounds(260, 180, 160, 30);

        installcalbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(installcalbox);
        installcalbox.setBounds(260, 220, 160, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Loan interest");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(30, 190, 120, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("loan limit(calculation installment) ");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(30, 230, 210, 20);

        jPanel4.setBackground(java.awt.Color.gray);
        jPanel4.setLayout(null);

        okbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        okbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ok.png"))); // NOI18N
        okbtn.setText("OK");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });
        jPanel4.add(okbtn);
        okbtn.setBounds(50, 20, 80, 30);

        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clean.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel4.add(clearbtn);
        clearbtn.setBounds(200, 20, 90, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(218, 218, 218))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llimitboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_llimitboxKeyPressed
        String   phone =llimitbox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                llimitbox.setEditable(true);
            }else{
                llimitbox.setEditable(false);
            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                llimitbox.setEditable(true);
            }else{
                llimitbox.setEditable(false);
            }
        }
    }//GEN-LAST:event_llimitboxKeyPressed

    private void mandatoryboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mandatoryboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mandatoryboxActionPerformed

    private void mandatoryboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mandatoryboxKeyPressed
        String   phone =mandatorybox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                mandatorybox.setEditable(true);
            }else{
                mandatorybox.setEditable(false);
            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                mandatorybox.setEditable(true);
            }else{
                mandatorybox.setEditable(false);
            }
        }
    }//GEN-LAST:event_mandatoryboxKeyPressed

    private void securitiesboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_securitiesboxKeyPressed
        String   phone =securitiesbox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                securitiesbox.setEditable(true);
            }else{
                securitiesbox.setEditable(false);
            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                securitiesbox.setEditable(true);
            }else{
                securitiesbox.setEditable(false);
            }
        }
    }//GEN-LAST:event_securitiesboxKeyPressed

    private void shareboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_shareboxKeyPressed
        String   phone =sharebox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                sharebox.setEditable(true);
            }else{
                sharebox.setEditable(false);
            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                sharebox.setEditable(true);
            }else{
                sharebox.setEditable(false);
            }
        }
    }//GEN-LAST:event_shareboxKeyPressed

    private void fromboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromboxKeyPressed
        String   phone =frombox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                frombox.setEditable(true);
            }else{
                frombox.setEditable(false);
            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                frombox.setEditable(true);
            }else{
                frombox.setEditable(false);
            }
        }
    }//GEN-LAST:event_fromboxKeyPressed

    private void toboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_toboxKeyPressed
        String   phone =tobox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                tobox.setEditable(true);
            }else{
                tobox.setEditable(false);
            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                tobox.setEditable(true);
            }else{
                tobox.setEditable(false);
            }
        }
    }//GEN-LAST:event_toboxKeyPressed

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtnActionPerformed
        if(llimitbox.getText().isEmpty() || mandatorybox.getText().isEmpty() || securitiesbox.getText().isEmpty() || sharebox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Some feilds are Empty");
        }else{
            int share = Integer.parseInt(sharebox.getText());
            int limit = Integer.parseInt(llimitbox.getText());
            int manda = Integer.parseInt(mandatorybox.getText());
            int sec = Integer.parseInt(securitiesbox.getText());
            int from = Integer.parseInt(frombox.getText());
            int to = Integer.parseInt(tobox.getText());
            int interest = Integer.parseInt(interestbox.getText());
            int cal = Integer.parseInt(installcalbox.getText());

            try {
                String sql = "UPDATE admin SET share='"+share+"',mandatory='"+manda+"',securities='"+sec+"',loan_limit='"+limit+"',frominstallment='"+from+"',toinstallment='"+to+"',callimit='"+cal+"',interest='"+interest+"'";
                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null,"updated succesfull");
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_okbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
             clear ();
    }//GEN-LAST:event_clearbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField frombox;
    private javax.swing.JTextField installcalbox;
    private javax.swing.JTextField interestbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField llimitbox;
    private javax.swing.JTextField mandatorybox;
    private javax.swing.JButton okbtn;
    private javax.swing.JTextField securitiesbox;
    private javax.swing.JTextField sharebox;
    private javax.swing.JTextField tobox;
    // End of variables declaration//GEN-END:variables
}
