/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import Code.DBconnect;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author acer
 */
public class child extends javax.swing.JInternalFrame {
    Connection con=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int hour,second,minute;
    int day,month,year;
    String timestr,yearstr;
    /**
     * Creates new form child
     */
    public child() {
        initComponents();
        con = DBconnect.connect();
        autoID();
        ((JTextField)dobbox.getDateEditor().getUiComponent()).setText("dd/MM/yyyy");
         setDateTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tnamebox = new javax.swing.JTextField();
        taddressbox = new javax.swing.JTextField();
        nicbox = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        phonenobox = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        childidbox = new javax.swing.JTextField();
        fnamebox = new javax.swing.JTextField();
        lnamebox = new javax.swing.JTextField();
        caddressbox = new javax.swing.JTextField();
        dobbox = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        searchbox = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        ctimebox = new javax.swing.JLabel();
        cdatebox = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Child");

        jPanel5.setBackground(new java.awt.Color(140, 212, 248));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trustee's Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), javax.swing.UIManager.getDefaults().getColor("Button.disabledBackground"))); // NOI18N
        jPanel5.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Name");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(20, 30, 40, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Address");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(20, 80, 60, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("NIC No");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 130, 41, 15);

        tnamebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel5.add(tnamebox);
        tnamebox.setBounds(170, 20, 190, 30);

        taddressbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        taddressbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taddressboxActionPerformed(evt);
            }
        });
        jPanel5.add(taddressbox);
        taddressbox.setBounds(170, 70, 190, 30);

        nicbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel5.add(nicbox);
        nicbox.setBounds(170, 120, 190, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Phone No");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(20, 180, 70, 15);

        phonenobox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        phonenobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phonenoboxActionPerformed(evt);
            }
        });
        phonenobox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonenoboxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phonenoboxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phonenoboxKeyTyped(evt);
            }
        });
        jPanel5.add(phonenobox);
        phonenobox.setBounds(170, 170, 190, 30);

        jPanel4.setBackground(new java.awt.Color(196, 225, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Child's Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12), javax.swing.UIManager.getDefaults().getColor("Button.disabledBackground"))); // NOI18N
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Child ID");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(20, 30, 90, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Frist Name");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 80, 90, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Last Name");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 130, 90, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Date Of Birth ");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 180, 90, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Address");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(20, 230, 90, 15);

        childidbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        childidbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                childidboxKeyPressed(evt);
            }
        });
        jPanel4.add(childidbox);
        childidbox.setBounds(180, 20, 190, 30);

        fnamebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.add(fnamebox);
        fnamebox.setBounds(180, 70, 190, 30);

        lnamebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.add(lnamebox);
        lnamebox.setBounds(180, 120, 190, 30);

        caddressbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.add(caddressbox);
        caddressbox.setBounds(180, 220, 190, 30);

        dobbox.setPreferredSize(new java.awt.Dimension(190, 30));
        jPanel4.add(dobbox);
        dobbox.setBounds(180, 170, 190, 30);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Enter Child ID"));
        jPanel6.setLayout(null);

        searchbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchboxKeyPressed(evt);
            }
        });
        jPanel6.add(searchbox);
        searchbox.setBounds(10, 30, 180, 30);

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbtnMouseClicked(evt);
            }
        });
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel6.add(searchbtn);
        searchbtn.setBounds(200, 30, 90, 30);

        addbtn.setBackground(new java.awt.Color(204, 204, 204));
        addbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insert-.png"))); // NOI18N
        addbtn.setText("ADD");
        addbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(204, 204, 204));
        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        updatebtn.setText("Update");
        updatebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebtnMouseClicked(evt);
            }
        });
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(204, 204, 204));
        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.setToolTipText("");
        deletebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(204, 204, 204));
        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clean.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        ctimebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ctimebox.setText("Time");

        cdatebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cdatebox.setText("Date");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sanasa2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(103, 103, 103)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cdatebox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ctimebox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cdatebox)
                            .addComponent(ctimebox))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taddressboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taddressboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taddressboxActionPerformed

    private void phonenoboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenoboxKeyPressed
        String   phone =phonenobox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                phonenobox.setEditable(true);
            }else{
                phonenobox.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                phonenobox.setEditable(true);
            }else{
                phonenobox.setEditable(false);
            }
        }
    }//GEN-LAST:event_phonenoboxKeyPressed

    private void phonenoboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenoboxKeyReleased
        phoneno();
    }//GEN-LAST:event_phonenoboxKeyReleased

    private void phonenoboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenoboxKeyTyped

    }//GEN-LAST:event_phonenoboxKeyTyped

    private void childidboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_childidboxKeyPressed
        String   phone =childidbox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<3){
                childidbox.setEditable(true);
            }else{
                childidbox.setEditable(false);

            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                childidbox.setEditable(true);
            }else{
                childidbox.setEditable(false);
            }
        }
    }//GEN-LAST:event_childidboxKeyPressed

    private void phonenoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonenoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonenoboxActionPerformed

    private void searchboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyPressed
        String   phone =searchbox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<3){
                searchbox.setEditable(true);
            }else{
                searchbox.setEditable(false);

            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                searchbox.setEditable(true);
            }else{
                searchbox.setEditable(false);
            }
        }
    }//GEN-LAST:event_searchboxKeyPressed

    private void searchbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbtnMouseClicked
        phoneno();
    }//GEN-LAST:event_searchbtnMouseClicked

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed

        if(searchbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Non-Member ID","Information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                pst = con.prepareStatement("SElECT childid,fname,lname,dob,address,trusteename,trusteeaddress,trusteenic,trusteephoneno FROM child WHERE childid=?");
                int search = Integer.parseInt(searchbox.getText());
                pst.setInt(1, search);
                rs = pst.executeQuery();

                if(rs.next()==false){
                    JOptionPane.showMessageDialog(null, "Search item not found","Information",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    String id = rs.getString("childid");
                    String fname =  rs.getString("fname");
                    String lname =  rs.getString("lname");
                    String nic =  rs.getString("trusteenic");
                    String address =  rs.getString("address");
                    String date = rs.getString("dob");
                    String tname =  rs.getString("trusteename");
                    String taddress =  rs.getString("trusteeaddress");
                    String phoneno =  rs.getString("trusteephoneno");

                    ((JTextField)dobbox.getDateEditor().getUiComponent()).setText(date);
                    childidbox.setText(id);
                    fnamebox.setText(fname);
                    lnamebox.setText(lname);
                    nicbox.setText(nic);
                    caddressbox.setText(address);
                    tnamebox.setText(tname);
                    taddressbox.setText(taddress);
                    phonenobox.setText(phoneno);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
        Date date;
        date = dobbox.getDate();
        try {
            String s =((JTextField)dobbox.getDateEditor().getUiComponent()).getText();

            if (s.equals("dd/MM/yyyy")){
                JOptionPane.showMessageDialog(null,"Please Enter Birthday", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_addbtnMouseClicked

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        SimpleDateFormat dformat = new SimpleDateFormat("dd/MM/yyyy");
        String dob =dformat.format(dobbox.getDate());

        String phoneno;
        String fname;
        String lname;
        String address;
        String taddress;
        String tname;
        int childid;
        String nic;
        String date;
        String time;

        phoneno = phonenobox.getText();
        fname = fnamebox.getText();
        lname = lnamebox.getText();
        address = caddressbox.getText();
        childid=Integer.parseInt(childidbox.getText());
        nic = nicbox.getText();
        date = cdatebox.getText();
        time= ctimebox.getText();
        taddress= taddressbox.getText();
        tname= tnamebox.getText();

        try {
            pst= con.prepareStatement("SELECT childid FROM child WHERE childid='"+childid+"'");
            rs=pst.executeQuery();
            if(rs.next()==true){
                JOptionPane.showMessageDialog(null, "Alredy Registered");
            }else{

                if(phoneno.isEmpty() || fname.isEmpty() || lname.isEmpty() || address.isEmpty() || childidbox.getText().isEmpty() || taddress.isEmpty() || nic.isEmpty() || date.isEmpty() || time.isEmpty() || tname.isEmpty() ){
                    JOptionPane.showMessageDialog(null, "Some fields are Empty","Information",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    pst = con.prepareStatement("SElECT accno FROM deaccount WHERE accno=?");
                    pst.setInt(1, childid);
                    rs = pst.executeQuery();
                    if( rs.next()==true){

                        String sq = "DELETE FROM deaccount WHERE accno='"+childid+"'";
                        pst = con.prepareStatement(sq);
                        pst.execute();

                        String sql = "INSERT INTO child (childid,fname,lname,dob,address,trusteename,trusteeaddress,trusteenic,trusteephoneno,date,time) VALUES ('"+childid+"','"+fname+"', '"+lname+"','"+dob+"','"+address+"','"+tname+"','"+taddress+"', '"+nic+"','"+phoneno+"','"+date+"','"+time+"')";
                        pst = con.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null,"Added Succesfull","Information",JOptionPane.INFORMATION_MESSAGE);
                        autoID();
                        clear();
                    }else{
                        String sql = "INSERT INTO child (childid,fname,lname,dob,address,trusteename,trusteeaddress,trusteenic,trusteephoneno,date,time) VALUES ('"+childid+"','"+fname+"', '"+lname+"','"+dob+"','"+address+"','"+tname+"','"+taddress+"', '"+nic+"','"+phoneno+"','"+date+"','"+time+"')";
                        pst = con.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null,"Added Succesfull","Information",JOptionPane.INFORMATION_MESSAGE);
                        autoID();
                        clear();
                    }

                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void updatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseClicked
        Date date;
        date = dobbox.getDate();
        try {
            String s =((JTextField)dobbox.getDateEditor().getUiComponent()).getText();

            if (s.equals("dd/MM/yyyy")){
                JOptionPane.showMessageDialog(null,"Please Enter Birthday", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_updatebtnMouseClicked

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        SimpleDateFormat dformat = new SimpleDateFormat("dd/MM/yyyy");
        String dob =dformat.format(dobbox.getDate());

        String phoneno;
        String fname;
        String lname;
        String address;
        String taddress;
        String tname;
        int childid;
        String nic;
        String date;
        String time;

        phoneno = phonenobox.getText();
        fname = fnamebox.getText();
        lname = lnamebox.getText();
        address = caddressbox.getText();
        childid=Integer.parseInt(childidbox.getText());
        nic = nicbox.getText();
        date = cdatebox.getText();
        time= ctimebox.getText();
        taddress= taddressbox.getText();
        tname= tnamebox.getText();

        if(phoneno.isEmpty() || fname.isEmpty() || lname.isEmpty() || address.isEmpty() || childidbox.getText().isEmpty() || taddress.isEmpty() || nic.isEmpty() || date.isEmpty() || time.isEmpty() || tname.isEmpty() ){
            JOptionPane.showMessageDialog(null, "Some fields are Empty","Information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                String sq = "UPDATE child SET fname='"+fname+"',lname='"+lname+"',address='"+address+"',dob='"+dob+"',trusteename='"+tname+"',trusteeaddress='"+taddress+"',trusteenic='"+nic+"',trusteephoneno='"+phoneno+"'  WHERE childid= '"+childid+"'";
                pst = con.prepareStatement(sq);
                pst.execute();
                JOptionPane.showMessageDialog(null,"Updated Succesfull ");
                clear();
                autoID();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        String name;
        int childid;
        String date;
        String time;

        name = fnamebox.getText() +" " + lnamebox.getText();
        childid=Integer.parseInt(childidbox.getText());
        date = cdatebox.getText();
        time= ctimebox.getText();

        int check= JOptionPane.showConfirmDialog(null, "Do You Want to Delete?");
        if(check==0){
            try {
                String sql = "INSERT INTO deaccount (accno,name,date,time) VALUES ('"+childid+"','"+name+"','"+date+"','"+time+"')";
                pst = con.prepareStatement(sql);
                pst.execute();

                String bal ="SELECT balance FROM childacc WHERE childid='"+childid+"' " ;
                pst = con.prepareStatement(bal);
                rs = pst.executeQuery();
                if(rs.next()==false){
                    int balance = 0;
                    String type= "Child";
                    int amount =0;
                }else{
                    // int amount= rs.getInt("balance");
                    String type= "Child";
                    int balance= rs.getInt("balance");
                    String with = "INSERT INTO withdraw (accno,name,amount,balance,acc_type,date,time) VALUES ('"+childid+"','"+name+"','"+balance+"','"+balance+"','"+type+"','"+date+"','"+time+"')";
                    pst = con.prepareStatement(with);
                    pst.execute();
                }
                String sq = "DELETE FROM child WHERE childid='"+childid+"'";
                pst = con.prepareStatement(sq);
                pst.execute();

                String s = "DELETE FROM childacc WHERE accno='"+childid+"'";
                pst = con.prepareStatement(s);
                pst.execute();

                JOptionPane.showMessageDialog(null,"Deleted Succesfull ");
                clear();
                autoID();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clear();
        autoID();
    }//GEN-LAST:event_clearbtnActionPerformed
    public void phoneno(){
         String   phone =phonenobox.getText();
        int length = phone.length();
        if(phone.isEmpty()){
           phonenobox.setBackground(Color.WHITE);
        }else{
            if(length<10){
                addbtn.setEnabled(false);
              phonenobox.setBackground(Color.RED);
              updatebtn.setEnabled(false);
            }else{
                if(length==10){
                    addbtn.setEnabled(true);
                    updatebtn.setEnabled(true);
                   phonenobox.setBackground(Color.GREEN);
                }else{
                    addbtn.setEnabled(false);
                    updatebtn.setEnabled(false);
                }
            }
        }
    }
    
    public void clear(){
        fnamebox.setText("");
        lnamebox.setText("");
        caddressbox.setText("");
        nicbox.setText("");
        phonenobox.setText("");
        ((JTextField)dobbox.getDateEditor().getUiComponent()).setText("dd/MM/yyyy");
        searchbox.setText("");
        taddressbox.setText("");
        tnamebox.setText("");
         phonenobox.setBackground(Color.WHITE);
    }
    
    public void autoID(){
       try{
       String sql ="SELECT max(childid)+1 FROM child " ;
       pst = con.prepareStatement(sql);
       rs = pst.executeQuery();
       rs.next();
        if ( rs.getString("max(childid)+1")==null){
     
       childidbox.setText("501" );
     }else{
        String max=rs.getString("max(childid)+1");
        childidbox.setText(max);
        }
    
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
       }
        
} 
    
     public void setDateTime() {
        
        Calendar c = Calendar.getInstance();
        hour= c.get(Calendar.HOUR_OF_DAY);
        if (hour >12)
            hour=hour -12;
        minute= c.get(Calendar.MINUTE);
        second= c.get(Calendar.SECOND);
        year= c.get(Calendar.YEAR);
        month= c.get(Calendar.MONTH);
        day= c.get(Calendar.DAY_OF_MONTH);
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date dat = c.getTime();
        timestr=sdf.format(dat);
        yearstr=df.format(dat);
        ctimebox.setText(timestr);
        cdatebox.setText(yearstr);
               

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField caddressbox;
    private javax.swing.JLabel cdatebox;
    private javax.swing.JTextField childidbox;
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel ctimebox;
    private javax.swing.JButton deletebtn;
    private com.toedter.calendar.JDateChooser dobbox;
    private javax.swing.JTextField fnamebox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField lnamebox;
    private javax.swing.JTextField nicbox;
    private javax.swing.JTextField phonenobox;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField taddressbox;
    private javax.swing.JTextField tnamebox;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
