/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import Code.DBconnect;
import static java.lang.System.in;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author acer
 */
public class loanpay extends javax.swing.JInternalFrame {

    Connection con=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int hour,second,minute;
    int day,month,year;
    String timestr,yearstr;
    /**
     * Creates new form loanpay
     */
    public loanpay() {
        initComponents();        
        con = DBconnect.connect();
        setDateTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        loanidbox = new javax.swing.JTextField();
        findbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idbox = new javax.swing.JLabel();
        namebox = new javax.swing.JLabel();
        nicbox = new javax.swing.JLabel();
        amountbox = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        monthamount = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        paybox = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        paybtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        datebox = new javax.swing.JLabel();
        timebox = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Loan Payments");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sanasa2.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(174, 199, 243));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(222, 224, 221));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Enter Loan ID or member ID"));
        jPanel4.setLayout(null);

        loanidbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.add(loanidbox);
        loanidbox.setBounds(40, 30, 230, 30);

        findbtn.setBackground(new java.awt.Color(204, 204, 204));
        findbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        findbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        findbtn.setText("Find");
        findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbtnActionPerformed(evt);
            }
        });
        jPanel4.add(findbtn);
        findbtn.setBounds(190, 70, 80, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(20, 20, 310, 110);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Loan ID");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 160, 100, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Full Name");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 200, 100, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NIC No");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 240, 100, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Loan Amount");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 280, 100, 15);

        idbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        idbox.setText("ID");
        jPanel3.add(idbox);
        idbox.setBounds(170, 160, 70, 14);

        namebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        namebox.setText("Name");
        jPanel3.add(namebox);
        namebox.setBounds(170, 200, 140, 14);

        nicbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nicbox.setText("NIC");
        jPanel3.add(nicbox);
        nicbox.setBounds(170, 240, 140, 14);

        amountbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        amountbox.setText("Amount");
        jPanel3.add(amountbox);
        amountbox.setBounds(170, 280, 90, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Monthly Installment Amount");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 320, 190, 15);

        monthamount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        monthamount.setText("Amount");
        jPanel3.add(monthamount);
        monthamount.setBounds(240, 320, 80, 14);

        jPanel5.setBackground(new java.awt.Color(190, 186, 185));
        jPanel5.setLayout(null);

        paybox.setBackground(new java.awt.Color(181, 244, 181));
        paybox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(paybox);
        paybox.setBounds(80, 40, 110, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setText("Rs");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(30, 40, 45, 40);

        paybtn.setBackground(new java.awt.Color(204, 204, 204));
        paybtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pay1.png"))); // NOI18N
        paybtn.setText("Pay");
        paybtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paybtnMouseClicked(evt);
            }
        });
        paybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybtnActionPerformed(evt);
            }
        });
        jPanel5.add(paybtn);
        paybtn.setBounds(50, 110, 110, 40);

        clearbtn.setBackground(new java.awt.Color(204, 204, 204));
        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clean.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel5.add(clearbtn);
        clearbtn.setBounds(50, 180, 110, 40);

        datebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        datebox.setText("Date");

        timebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        timebox.setText("Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(202, 202, 202))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(datebox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timebox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datebox)
                    .addComponent(timebox))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbtnActionPerformed
        if(loanidbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Member ID or Loan ID" ,"Information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                pst = con.prepareStatement("SElECT memberid,loanid,name,nic,amount,installments FROM loan WHERE memberid=? OR loanid=? ");
                String search = loanidbox.getText();
                pst.setString(1, search);
                pst.setString(2, search);
                rs = pst.executeQuery();
                if(rs.next()==false){
                    JOptionPane.showMessageDialog(null, "No loan has been obtained for this number" ,"Information",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    String loanid = rs.getString("loanid");
                    String name = rs.getString("name");
                    String nic = rs.getString("nic");
                    int amount = rs.getInt("amount");
                    int install = rs.getInt("installments");

                    idbox.setText(loanid);
                    namebox.setText(name);
                    nicbox.setText(nic);
                    amountbox.setText(String.valueOf(amount));
                    float month = ((float)amount/install);
                    float rountmonth =Math.round(month*100/100);
                    int m = (int)rountmonth;
                    monthamount.setText(String.valueOf(m));

                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_findbtnActionPerformed

    private void paybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybtnActionPerformed
        if(loanidbox.getText().isEmpty() || idbox.getText().equals("ID") || paybox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Some fields are Empty" ,"Information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                String memid = loanidbox.getText();
                String loanid = idbox.getText();
                String name = namebox.getText();
                String nic = nicbox.getText();
                String date = datebox.getText();
                String time = timebox.getText();
                int lamount = Integer.parseInt(amountbox.getText());
                int payamount = Integer.parseInt(paybox.getText());

                String sql = "INSERT INTO loanpay (memberid,loanid,name,nicno,paid_amount,current_loan,date,time) VALUES ('"+memid+"','"+loanid+"','"+name+"','"+nic+"','"+payamount+"','"+lamount+"','"+date+"','"+time+"')";
                pst = con.prepareStatement(sql);
                pst.execute();

                int reduction = lamount - payamount;
                if(reduction==0){
                    String sq = "DELETE FROM loan WHERE loanid='"+loanid+"'";
                    pst = con.prepareStatement(sq);
                    pst.execute();

                    String s = "DELETE FROM guarantor WHERE loanid='"+loanid+"'";
                    pst = con.prepareStatement(s);
                    pst.execute();

                    JOptionPane.showMessageDialog(null,  "Your loan has been repaid" ,"Information",JOptionPane.INFORMATION_MESSAGE);
                    clear();
                }else{

                    pst = con.prepareStatement("SElECT installments FROM loan WHERE memberid=? OR loanid=? ");
                    String search = loanidbox.getText();
                    pst.setString(1, search);
                    pst.setString(2, search);
                    rs = pst.executeQuery();
                    rs.next();
                    int install = rs.getInt("installments");
                    int nowinstall = install-1;
                    rs.close();
                    String sql1 = "UPDATE loan SET amount='"+reduction+"',installments='"+nowinstall+"'  WHERE loanid= '"+loanid+"' ";
                    pst = con.prepareStatement(sql1);
                    pst.execute();
                    JOptionPane.showMessageDialog(null,  "Your payment is completed.The current loan amount is Rs."+reduction+"/=" ,"Information",JOptionPane.INFORMATION_MESSAGE);
                    clear();
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_paybtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clear();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void paybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybtnMouseClicked
       if(loanidbox.getText().isEmpty() || idbox.getText().equals("ID") || paybox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Some fields are Empty" ,"Information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                String memid = loanidbox.getText();
                String loanid = idbox.getText();
                String name = namebox.getText();
                String nic = nicbox.getText();
                String date = datebox.getText();
                String time = timebox.getText();
                int lamount = Integer.parseInt(amountbox.getText());
                int payamount = Integer.parseInt(paybox.getText());

                String sql = "INSERT INTO loanpay (memberid,loanid,name,nicno,paid_amount,current_loan,date,time) VALUES ('"+memid+"','"+loanid+"','"+name+"','"+nic+"','"+payamount+"','"+lamount+"','"+date+"','"+time+"')";
                pst = con.prepareStatement(sql);
                pst.execute();

                int reduction = lamount - payamount;
                if(reduction==0){
                    String sq = "DELETE FROM loan WHERE loanid='"+loanid+"'";
                    pst = con.prepareStatement(sq);
                    pst.execute();

                    String s = "DELETE FROM guarantor WHERE loanid='"+loanid+"'";
                    pst = con.prepareStatement(s);
                    pst.execute();

                    JOptionPane.showMessageDialog(null,  "Your loan has been repaid" ,"Information",JOptionPane.INFORMATION_MESSAGE);
                    clear();
                }else{

                    pst = con.prepareStatement("SElECT installments FROM loan WHERE memberid=? OR loanid=? ");
                    String search = loanidbox.getText();
                    pst.setString(1, search);
                    pst.setString(2, search);
                    rs = pst.executeQuery();
                    rs.next();
                    int install = rs.getInt("installments");
                    int nowinstall = install-1;
                    rs.close();
                    String sql1 = "UPDATE loan SET amount='"+reduction+"',installments='"+nowinstall+"'  WHERE loanid= '"+loanid+"' ";
                    pst = con.prepareStatement(sql1);
                    pst.execute();
                    JOptionPane.showMessageDialog(null,  "Your payment is completed.The current loan amount is Rs."+reduction+"/=" ,"Information",JOptionPane.INFORMATION_MESSAGE);
                    clear();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e ,"Information",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_paybtnMouseClicked

    public void clear(){
        loanidbox.setText("");
        idbox.setText("ID");
         namebox.setText("name");
          nicbox.setText("NIC");
         amountbox.setText("Amount");
         paybox.setText("");
         monthamount.setText("Amount");
    }
    public void setDateTime() {
        
        Calendar c = Calendar.getInstance();
        hour= c.get(Calendar.HOUR_OF_DAY);
        if (hour >12)
            hour=hour -12;
        minute= c.get(Calendar.MINUTE);
        second= c.get(Calendar.SECOND);
        year= c.get(Calendar.YEAR);
        month= c.get(Calendar.MONTH);
        day= c.get(Calendar.DAY_OF_MONTH);
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date dat = c.getTime();
        timestr=sdf.format(dat);
        yearstr=df.format(dat);
        timebox.setText(timestr);
        datebox.setText(yearstr);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountbox;
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel datebox;
    private javax.swing.JButton findbtn;
    private javax.swing.JLabel idbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField loanidbox;
    private javax.swing.JLabel monthamount;
    private javax.swing.JLabel namebox;
    private javax.swing.JLabel nicbox;
    private javax.swing.JTextField paybox;
    private javax.swing.JButton paybtn;
    private javax.swing.JLabel timebox;
    // End of variables declaration//GEN-END:variables
}
