/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import Code.DBconnect;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class loan extends javax.swing.JInternalFrame {
    Connection con=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int hour,second,minute;
    int day,month,year;
    String timestr,yearstr;
    /**
     * Creates new form loan
     */
    public loan() {
        initComponents();
        con = DBconnect.connect();
        checkbox();
        setDateTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nextpanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        memidbox = new javax.swing.JTextField();
        findbox = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        loanidbox = new javax.swing.JLabel();
        namebox = new javax.swing.JLabel();
        addressbox = new javax.swing.JLabel();
        phonenobox = new javax.swing.JLabel();
        agebox = new javax.swing.JTextField();
        amountbox = new javax.swing.JTextField();
        instbox = new javax.swing.JTextField();
        nicbox = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        searchbox = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        nextbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        datebox = new javax.swing.JLabel();
        timebox = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        g1searchbox = new javax.swing.JTextField();
        g1findbtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        g1idbox = new javax.swing.JLabel();
        g1namebox = new javax.swing.JLabel();
        g1addressbox = new javax.swing.JLabel();
        g1nicbox = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        g2searchbox = new javax.swing.JTextField();
        g2findbtn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        g2idbox = new javax.swing.JLabel();
        g2namebox = new javax.swing.JLabel();
        g2addressbox = new javax.swing.JLabel();
        g2nicbox = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        checkbox = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        mendabox = new javax.swing.JTextField();
        secbox = new javax.swing.JTextField();
        insertbtn = new javax.swing.JButton();
        gupdatebtn = new javax.swing.JButton();
        gclearbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sanasa2.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Loan");

        nextpanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(205, 207, 202));
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(185, 193, 185));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Enter Member ID"));
        jPanel5.setLayout(null);

        memidbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.add(memidbox);
        memidbox.setBounds(20, 30, 220, 30);

        findbox.setBackground(new java.awt.Color(204, 204, 204));
        findbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        findbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        findbox.setText("Find");
        findbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findboxActionPerformed(evt);
            }
        });
        jPanel5.add(findbox);
        findbox.setBounds(270, 30, 80, 30);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(30, 20, 370, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Loan ID");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(30, 120, 170, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Full Name");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(30, 160, 170, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Address");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(30, 200, 170, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Phone No");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(30, 240, 170, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("NIC No");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(30, 280, 170, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Age");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(30, 320, 170, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Loan Amount");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(30, 360, 180, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Number of loan installments");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(30, 400, 180, 15);

        loanidbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loanidbox.setForeground(new java.awt.Color(51, 0, 255));
        loanidbox.setText("ID");
        jPanel4.add(loanidbox);
        loanidbox.setBounds(220, 120, 90, 14);

        namebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        namebox.setText("Name");
        jPanel4.add(namebox);
        namebox.setBounds(220, 160, 140, 14);

        addressbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addressbox.setText("Address");
        jPanel4.add(addressbox);
        addressbox.setBounds(220, 200, 190, 14);

        phonenobox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        phonenobox.setText("Phone no");
        jPanel4.add(phonenobox);
        phonenobox.setBounds(220, 240, 110, 14);

        agebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        agebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageboxKeyPressed(evt);
            }
        });
        jPanel4.add(agebox);
        agebox.setBounds(220, 310, 180, 30);

        amountbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        amountbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                amountboxKeyPressed(evt);
            }
        });
        jPanel4.add(amountbox);
        amountbox.setBounds(220, 350, 180, 30);

        instbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        instbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                instboxKeyPressed(evt);
            }
        });
        jPanel4.add(instbox);
        instbox.setBounds(220, 390, 180, 30);

        nicbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nicbox.setText("NIC No");
        jPanel4.add(nicbox);
        nicbox.setBounds(220, 280, 130, 14);

        jPanel14.setBackground(new java.awt.Color(185, 193, 185));
        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Enter Member ID or Loan ID"));
        jPanel14.setLayout(null);

        searchbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel14.add(searchbox);
        searchbox.setBounds(20, 20, 140, 30);

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel14.add(searchbtn);
        searchbtn.setBounds(170, 20, 90, 30);

        nextbtn.setBackground(new java.awt.Color(204, 204, 204));
        nextbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nextbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/next.png"))); // NOI18N
        nextbtn.setText("Next");
        nextbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnActionPerformed(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(204, 204, 204));
        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clean.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nextbtn.png"))); // NOI18N
        jLabel14.setText("See next page");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        datebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        datebox.setText("Date");

        timebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        timebox.setText("Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nextbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(datebox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(timebox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(nextbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datebox)
                    .addComponent(timebox))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        nextpanel.addTab("First page", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Details of the guarantors");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(213, 210, 210));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Frist guarantor details"));
        jPanel8.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(191, 187, 187));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Enter Member ID"));
        jPanel11.setLayout(null);

        g1searchbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel11.add(g1searchbox);
        g1searchbox.setBounds(20, 20, 160, 30);

        g1findbtn.setBackground(new java.awt.Color(204, 204, 204));
        g1findbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g1findbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        g1findbtn.setText("Find");
        g1findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1findbtnActionPerformed(evt);
            }
        });
        jPanel11.add(g1findbtn);
        g1findbtn.setBounds(190, 20, 80, 30);

        jPanel8.add(jPanel11);
        jPanel11.setBounds(20, 30, 280, 70);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("ID");
        jPanel8.add(jLabel18);
        jLabel18.setBounds(30, 130, 80, 15);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Full Name");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(30, 170, 80, 15);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Address");
        jPanel8.add(jLabel20);
        jLabel20.setBounds(30, 220, 80, 15);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("NIC No");
        jPanel8.add(jLabel21);
        jLabel21.setBounds(30, 270, 80, 15);

        g1idbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g1idbox.setText("ID");
        jPanel8.add(g1idbox);
        g1idbox.setBounds(140, 130, 110, 14);

        g1namebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g1namebox.setText("name");
        jPanel8.add(g1namebox);
        g1namebox.setBounds(140, 170, 130, 14);

        g1addressbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g1addressbox.setText("address");
        jPanel8.add(g1addressbox);
        g1addressbox.setBounds(140, 220, 120, 14);

        g1nicbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g1nicbox.setText("nic no");
        jPanel8.add(g1nicbox);
        g1nicbox.setBounds(140, 270, 120, 14);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(10, 10, 320, 300);

        jPanel9.setBackground(new java.awt.Color(213, 210, 210));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Second gurarantor details"));
        jPanel9.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(191, 187, 187));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Enter Member ID"));
        jPanel12.setLayout(null);

        g2searchbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel12.add(g2searchbox);
        g2searchbox.setBounds(20, 20, 160, 30);

        g2findbtn.setBackground(new java.awt.Color(204, 204, 204));
        g2findbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g2findbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        g2findbtn.setText("Find");
        g2findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g2findbtnActionPerformed(evt);
            }
        });
        jPanel12.add(g2findbtn);
        g2findbtn.setBounds(185, 20, 72, 30);

        jPanel9.add(jPanel12);
        jPanel12.setBounds(20, 30, 270, 70);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Full Name");
        jPanel9.add(jLabel22);
        jLabel22.setBounds(30, 170, 80, 15);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Address");
        jPanel9.add(jLabel23);
        jLabel23.setBounds(30, 220, 80, 15);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("NIC No");
        jPanel9.add(jLabel24);
        jLabel24.setBounds(30, 270, 80, 15);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("ID");
        jPanel9.add(jLabel25);
        jLabel25.setBounds(30, 130, 80, 15);

        g2idbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g2idbox.setText("ID");
        jPanel9.add(g2idbox);
        g2idbox.setBounds(140, 130, 60, 14);

        g2namebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g2namebox.setText("name");
        jPanel9.add(g2namebox);
        g2namebox.setBounds(140, 170, 130, 14);

        g2addressbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g2addressbox.setText("address");
        jPanel9.add(g2addressbox);
        g2addressbox.setBounds(140, 220, 140, 14);

        g2nicbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        g2nicbox.setText("nic no");
        jPanel9.add(g2nicbox);
        g2nicbox.setBounds(140, 270, 140, 14);

        jPanel7.add(jPanel9);
        jPanel9.setBounds(340, 10, 310, 300);

        jPanel13.setBackground(new java.awt.Color(213, 210, 210));
        jPanel13.setLayout(null);

        checkbox.setBackground(new java.awt.Color(213, 210, 210));
        checkbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        checkbox.setText("Mendatory deposits and securities deposits are paid");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel13.add(checkbox);
        checkbox.setBounds(180, 10, 330, 19);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Mendatory deposit Amount");
        jPanel13.add(jLabel12);
        jLabel12.setBounds(10, 50, 160, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Securities deposit Amount");
        jPanel13.add(jLabel13);
        jLabel13.setBounds(320, 50, 150, 14);

        mendabox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel13.add(mendabox);
        mendabox.setBounds(170, 40, 130, 30);

        secbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel13.add(secbox);
        secbox.setBounds(480, 40, 130, 30);

        insertbtn.setBackground(new java.awt.Color(204, 204, 204));
        insertbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insertbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insert-.png"))); // NOI18N
        insertbtn.setText("Insert");
        insertbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });

        gupdatebtn.setBackground(new java.awt.Color(204, 204, 204));
        gupdatebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gupdatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        gupdatebtn.setText("Update");
        gupdatebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gupdatebtnActionPerformed(evt);
            }
        });

        gclearbtn.setBackground(new java.awt.Color(204, 204, 204));
        gclearbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gclearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clean.png"))); // NOI18N
        gclearbtn.setText("Clear");
        gclearbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gclearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gclearbtnActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(204, 204, 204));
        backbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backbtn.setText("Back");
        backbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(gupdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(gclearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gupdatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gclearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        nextpanel.addTab("Second page", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(226, 226, 226)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(nextpanel)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findboxActionPerformed
        if(memidbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Member ID", "Information", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                pst = con.prepareStatement("SElECT memberid,fname,lname,address,nicno,phoneno FROM member WHERE memberid=?");
                int search = Integer.parseInt(memidbox.getText());
                pst.setInt(1, search);
                rs = pst.executeQuery();
                if(rs.next()==false){
                    JOptionPane.showMessageDialog(null, "Search item not found", "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    int id =rs.getInt("memberid");
                    String fname = rs.getString("fname");
                    String lname = rs.getString("lname");
                    String address = rs.getString("address");
                    String nic = rs.getString("nicno");
                    String phone = rs.getString("phoneno");

                    loanidbox.setText("L"+String.valueOf(id));
                    namebox.setText(fname+" "+lname);
                    addressbox.setText(address);
                    phonenobox.setText(phone);
                    nicbox.setText(nic);
                    // memidbox.setText("");
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_findboxActionPerformed

    private void ageboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageboxKeyPressed
        String   phone =agebox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                agebox.setEditable(true);
            }else{
                agebox.setEditable(false);
            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                agebox.setEditable(true);
            }else{
                agebox.setEditable(false);
            }
        }
    }//GEN-LAST:event_ageboxKeyPressed

    private void amountboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountboxKeyPressed
        String   phone =amountbox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                amountbox.setEditable(true);
            }else{
                amountbox.setEditable(false);
            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                amountbox.setEditable(true);
            }else{
                amountbox.setEditable(false);
            }
        }
    }//GEN-LAST:event_amountboxKeyPressed

    private void instboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_instboxKeyPressed
        String   phone =instbox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                instbox.setEditable(true);
            }else{
                instbox.setEditable(false);
            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                instbox.setEditable(true);
            }else{
                instbox.setEditable(false);
            }
        }
    }//GEN-LAST:event_instboxKeyPressed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        search();
        searchbox.setText("");
    }//GEN-LAST:event_searchbtnActionPerformed

    private void nextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbtnActionPerformed

        String loanid = loanidbox.getText();
        String name = namebox.getText();
        String address = addressbox.getText();
        String nic = nicbox.getText();

        if(loanid.equals("ID") || name.equals("Name") || address.equals("Address") || nic.equals("NIC No") || phonenobox.getText().equals("Phone no") || agebox.getText().isEmpty() || amountbox.getText().isEmpty() || instbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Some fields are Empty");
        }else{

            try {
                pst = con.prepareStatement("SElECT loanid FROM loan WHERE loanid=?");
                String search = loanidbox.getText();
                pst.setString(1, search);
                rs = pst.executeQuery();
                if(rs.next()==false){
                    pst = con.prepareStatement("SElECT loan_limit,frominstallment,toinstallment,callimit FROM admin ");
                    rs = pst.executeQuery();
                    rs.next();
                    int limit = rs.getInt("loan_limit");
                    int from = rs.getInt("frominstallment");
                    int to = rs.getInt("toinstallment");
                    int cal = rs.getInt("callimit");
                    int sum =limit*cal/100;
                    int amount = Integer.parseInt(amountbox.getText());
                    if(amount<=sum){
                        int ints = Integer.parseInt(instbox.getText());
                        if(ints<=from){
                            nextpanel.setSelectedIndex(1);
                        }else{
                            JOptionPane.showMessageDialog(null, "The loan installments exceed the amount you receive");
                        }
                    }else{
                        int ints = Integer.parseInt(instbox.getText());
                        if(ints<=to){
                            nextpanel.setSelectedIndex(1);
                        }else{
                            JOptionPane.showMessageDialog(null, "The maximum number of installment that the bank can pay to repay a loan has been exceeded");
                        }
                    }
                }else{
                    pst = con.prepareStatement("SElECT amount,installments FROM loan WHERE loanid=?");
                    String sear = loanidbox.getText();
                    pst.setString(1, sear);
                    rs = pst.executeQuery();
                    rs.next();
                    int loanbal = rs.getInt("amount");
                    int instbal =rs.getInt("installments");
                    rs.close();
                    pst = con.prepareStatement("SElECT loan_limit FROM admin ");
                    rs = pst.executeQuery();
                    rs.next();
                    int limit = rs.getInt("loan_limit");
                    rs.close();
                    int amount = Integer.parseInt(amountbox.getText());
                    int ints = Integer.parseInt(instbox.getText());
                    int lon = amount +loanbal;
                    int installball = ints+instbal;
                    if (lon<=limit){
                        int check= JOptionPane.showConfirmDialog(null, "You have already abtained a loan of Rs."+loanbal+"/=. Therefore,if you get this amount, Your loan amount will be updated to Rs."+lon+"/=. Do you want to get that loan?","Information" ,JOptionPane.INFORMATION_MESSAGE);
                        if(check==0){
                            amountbox.setText(String.valueOf(lon));
                            instbox.setText(String.valueOf(installball));
                            nextpanel.setSelectedIndex(1);
                        }else{
                            clear();
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "You have already abtained a loan of Rs."+loanbal+"/=. Then you personal credit limit will be exceeded. Therefore you will not be able to get this loan amount " ,"ERROR",JOptionPane.ERROR_MESSAGE);
                    }

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_nextbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clear();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        nextpanel.setSelectedIndex(1);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        checkbox();
    }//GEN-LAST:event_checkboxActionPerformed

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
        String g1name =g1namebox.getText();
        String g1address =g1addressbox.getText();
        String g1nic =g1nicbox.getText();
        String g2name =g2namebox.getText();
        String g2address =g2addressbox.getText();
        String g2nic =g2nicbox.getText();
        String date =datebox.getText();
        String time =timebox.getText();
        try {
            pst = con.prepareStatement("SElECT memberid FROM loan WHERE memberid= ?");
            int srch =  Integer.parseInt(memidbox.getText());
            pst.setInt(1, srch);
            rs = pst.executeQuery();
            if(rs.next()==false){
                if(checkbox.isSelected()){
                    if(g1idbox.getText().equals("ID") || g2idbox.getText().equals("ID") || g1name.equals("name") || g1address.equals("address") || g1nic.equals("nic no") || g2name.equals("name") || g2address.equals("address") || g2nic.equals("nic no") || mendabox.getText().isEmpty() || secbox.getText().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Some feilds are Empty","Information",JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        int amount = Integer.parseInt(amountbox.getText());

                        try {
                            pst = con.prepareStatement("SElECT mandatory,securities,interest,loan_limit,toinstallment FROM admin ");
                            rs = pst.executeQuery();
                            rs.next();
                            int manda = rs.getInt("mandatory");
                            int sec = rs.getInt("securities");
                            int interest = rs.getInt("interest");
                            int llimit = rs.getInt("loan_limit");
                            int to = rs.getInt("toinstallment");
                            rs.close();

                            int valuemanda = amount * manda/100;
                            int valuesec = amount * sec/100;
                            int withinterest = amount * interest/100;
                            int mandaamount = Integer.parseInt(mendabox.getText());
                            int secamount = Integer.parseInt(secbox.getText());
                            int redmanda =valuemanda-mandaamount;
                            int redsec =valuesec-secamount;
                            int sum = redmanda+ redsec;
                            int curenntamount = amount+sum+withinterest ;
                            int memid = Integer.parseInt(memidbox.getText());
                            String loanid = loanidbox.getText();
                            String name = namebox.getText();
                            String address = addressbox.getText();
                            String nic = nicbox.getText();
                            int age = Integer.parseInt(agebox.getText());
                            String phoneno= phonenobox.getText();
                            int intstall = Integer.parseInt(instbox.getText());
                            int g1id = Integer.parseInt(g1idbox.getText());
                            int g2id = Integer.parseInt(g2idbox.getText());

                            if(curenntamount>=llimit+1){

                                JOptionPane.showMessageDialog(null, "Your maximum credit limit has been exceeded");
                            }else{
                                if(intstall>to){
                                    JOptionPane.showMessageDialog(null, "Your maximum loan installments have been exceeded");
                                }else{
                                    String sql = "INSERT INTO loan (memberid,loanid,name,address,phoneno,nic,age,amount,installments,mendaamount,secamount,date,time) VALUES ('"+memid+"','"+loanid+"','"+name+"', '"+address+"','"+phoneno+"','"+nic+"','"+age+"','"+curenntamount+"','"+intstall+"','"+mandaamount+"','"+secamount+"','"+date+"','"+time+"')";
                                    pst = con.prepareStatement(sql);
                                    pst.execute();

                                    String sq = "INSERT INTO guarantor (memid,loanid,fguarantorid,lguarantorid,fguarantorname,lguarantorname,fguarantoradd,lguarantoradd,fguarantornic,lguarantornic) VALUES ('"+memid+"','"+loanid+"','"+g1id+"', '"+g2id+"','"+g1name+"','"+g2name+"','"+g1address+"','"+g2address+"','"+g1nic+"','"+g2nic+"')";
                                    pst = con.prepareStatement(sq);
                                    pst.execute();

                                    JOptionPane.showMessageDialog(null, "Insert succesfull","Information",JOptionPane.INFORMATION_MESSAGE);
                                    clear();
                                    clear2();
                                }
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                }else{
                    //  JOptionPane.showMessageDialog(null, "Skkkkkkkkkkkkkk","Information",JOptionPane.INFORMATION_MESSAGE);
                    if(g1idbox.getText().equals("ID") || g2idbox.getText().equals("ID") || g1name.equals("name") || g1address.equals("address") || g1nic.equals("nic no") || g2name.equals("name") || g2address.equals("address") || g2nic.equals("nic no")){
                        JOptionPane.showMessageDialog(null, "Some feilds are Empty","Information",JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        try {
                            pst = con.prepareStatement("SElECT mandatory,securities,interest,loan_limit,toinstallment FROM admin ");
                            rs = pst.executeQuery();
                            rs.next();
                            int manda = rs.getInt("mandatory");
                            int sec = rs.getInt("securities");
                            int interest = rs.getInt("interest");
                            int llimit = rs.getInt("loan_limit");
                            int to = rs.getInt("toinstallment");
                            rs.close();
                            int amount = Integer.parseInt(amountbox.getText());
                            int valuemanda = amount * manda/100;
                            int valuesec = amount * sec/100;
                            int withinterest = amount * interest/100;
                            int sum = valuemanda+ valuesec;
                            int curenntamount = amount+sum +withinterest;
                            int mandaamount =0;
                            int secamount =0;
                            int memid = Integer.parseInt(memidbox.getText());
                            String loanid = loanidbox.getText();
                            String name = namebox.getText();
                            String address = addressbox.getText();
                            String nic = nicbox.getText();
                            int age = Integer.parseInt(agebox.getText());
                            String phoneno= phonenobox.getText();
                            int intstall = Integer.parseInt(instbox.getText());
                            int g1id = Integer.parseInt(g1idbox.getText());
                            int g2id = Integer.parseInt(g2idbox.getText());
                            if(curenntamount>=llimit+1){

                                JOptionPane.showMessageDialog(null, "Your maximum credit limit has been exceeded");
                            }else{
                                if(intstall>to){
                                    JOptionPane.showMessageDialog(null, "Your maximum loan installments have been exceeded");
                                }else{
                                    String sql = "INSERT INTO loan (memberid,loanid,name,address,phoneno,nic,age,amount,installments,mendaamount,secamount,date,time) VALUES ('"+memid+"','"+loanid+"','"+name+"', '"+address+"','"+phoneno+"','"+nic+"','"+age+"','"+curenntamount+"','"+intstall+"','"+mandaamount+"','"+secamount+"','"+date+"','"+time+"')";
                                    pst = con.prepareStatement(sql);
                                    pst.execute();

                                    String sq = "INSERT INTO guarantor (memid,loanid,fguarantorid,lguarantorid,fguarantorname,lguarantorname,fguarantoradd,lguarantoradd,fguarantornic,lguarantornic) VALUES ('"+memid+"','"+loanid+"','"+g1id+"', '"+g2id+"','"+g1name+"','"+g2name+"','"+g1address+"','"+g2address+"','"+g1nic+"','"+g2nic+"')";
                                    pst = con.prepareStatement(sq);
                                    pst.execute();
                                    JOptionPane.showMessageDialog(null, "Insert succesfull","Information",JOptionPane.INFORMATION_MESSAGE);
                                    clear();
                                    clear2();
                                }
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                }
            }else{
                if(checkbox.isSelected()){
                    if(g1idbox.getText().equals("ID") || g2idbox.getText().equals("ID") || g1name.equals("name") || g1address.equals("address") || g1nic.equals("nic no") || g2name.equals("name") || g2address.equals("address") || g2nic.equals("nic no") || mendabox.getText().isEmpty() || secbox.getText().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Some feilds are Empty","Information",JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        int amount = Integer.parseInt(amountbox.getText());

                        try {
                            pst = con.prepareStatement("SElECT mandatory,securities,interest,loan_limit,toinstallment FROM admin ");
                            rs = pst.executeQuery();
                            rs.next();
                            int manda = rs.getInt("mandatory");
                            int sec = rs.getInt("securities");
                            int interest = rs.getInt("interest");
                            int llimit = rs.getInt("loan_limit");
                            int to = rs.getInt("toinstallment");
                            rs.close();
                            pst = con.prepareStatement("SElECT mendaamount,secamount FROM loan WHERE loanid=?");
                            String sear = loanidbox.getText();
                            pst.setString(1, sear);
                            rs = pst.executeQuery();
                            rs.next();
                            int mandabal = rs.getInt("mendaamount");
                            int secbal =rs.getInt("secamount");
                            rs.close();

                            int valuemanda = amount * manda/100;
                            int valuesec = amount * sec/100;
                            int withinterest = amount * interest/100;
                            int mandaamount = Integer.parseInt(mendabox.getText());
                            int secamount = Integer.parseInt(secbox.getText());
                            int currutmanda = mandabal+mandaamount;
                            int currutsec = secbal+secamount;
                            int redmanda =valuemanda-mandaamount;
                            int redsec =valuesec-secamount;
                            int sum = redmanda+ redsec;
                            int curenntamount = amount+sum+withinterest ;
                            int memid = Integer.parseInt(memidbox.getText());
                            int age = Integer.parseInt(agebox.getText());
                            int intstall = Integer.parseInt(instbox.getText());
                            int g1id = Integer.parseInt(g1idbox.getText());
                            int g2id = Integer.parseInt(g2idbox.getText());

                            if(curenntamount>=llimit+1){

                                JOptionPane.showMessageDialog(null, "Your maximum credit limit has been exceeded");
                            }else{
                                if(intstall>to){
                                    JOptionPane.showMessageDialog(null, "Your maximum loan installments have been exceeded");
                                }else{
                                    String sql = "UPDATE loan SET age='"+age+"',amount='"+curenntamount+"',installments='"+intstall+"',mendaamount='"+currutmanda+"',secamount='"+currutsec+"',date='"+date+"',time='"+time+"' WHERE memberid='"+memid+"'";
                                    pst = con.prepareStatement(sql);
                                    pst.execute();

                                    String sq = "UPDATE guarantor SET fguarantorid='"+g1id+"',lguarantorid='"+g2id+"',fguarantorname='"+g1name+"',lguarantorname='"+g2name+"',fguarantoradd='"+g1address+"',lguarantoradd='"+g2address+"',fguarantornic='"+g1nic+"',lguarantornic='"+g2nic+"' WHERE memid='"+memid+"'";
                                    pst = con.prepareStatement(sq);
                                    pst.execute();

                                    JOptionPane.showMessageDialog(null, "Insert succesfull","Information",JOptionPane.INFORMATION_MESSAGE);
                                    clear();
                                    clear2();
                                }
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                }else{
                    //  JOptionPane.showMessageDialog(null, "Skkkkkkkkkkkkkk","Information",JOptionPane.INFORMATION_MESSAGE);
                    if(g1idbox.getText().equals("ID") || g2idbox.getText().equals("ID") || g1name.equals("name") || g1address.equals("address") || g1nic.equals("nic no") || g2name.equals("name") || g2address.equals("address") || g2nic.equals("nic no")){
                        JOptionPane.showMessageDialog(null, "Some feilds are Empty","Information",JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        try {
                            pst = con.prepareStatement("SElECT mandatory,securities,interest,loan_limit,toinstallment FROM admin ");
                            rs = pst.executeQuery();
                            rs.next();
                            int manda = rs.getInt("mandatory");
                            int sec = rs.getInt("securities");
                            int interest = rs.getInt("interest");
                            int llimit = rs.getInt("loan_limit");
                            int to = rs.getInt("toinstallment");
                            rs.close();
                            int amount = Integer.parseInt(amountbox.getText());
                            int valuemanda = amount * manda/100;
                            int valuesec = amount * sec/100;
                            int withinterest = amount * interest/100;
                            int sum = valuemanda+ valuesec;
                            int curenntamount = amount+sum +withinterest;
                            int mandaamount =0;
                            int secamount =0;
                            int memid = Integer.parseInt(memidbox.getText());
                            int age = Integer.parseInt(agebox.getText());
                            int intstall = Integer.parseInt(instbox.getText());
                            int g1id = Integer.parseInt(g1idbox.getText());
                            int g2id = Integer.parseInt(g2idbox.getText());
                            if(curenntamount>=llimit+1){

                                JOptionPane.showMessageDialog(null, "Your maximum credit limit has been exceeded");
                            }else{
                                if(intstall>to){
                                    JOptionPane.showMessageDialog(null, "Your maximum loan installments have been exceeded");
                                }else{
                                    String sql = "UPDATE loan SET age='"+age+"',amount='"+curenntamount+"',installments='"+intstall+"',date='"+date+"',time='"+time+"' WHERE memberid='"+memid+"'";
                                    pst = con.prepareStatement(sql);
                                    pst.execute();

                                    String sq = "UPDATE guarantor SET fguarantorid='"+g1id+"',lguarantorid='"+g2id+"',fguarantorname='"+g1name+"',lguarantorname='"+g2name+"',fguarantoradd='"+g1address+"',lguarantoradd='"+g2address+"',fguarantornic='"+g1nic+"',lguarantornic='"+g2nic+"' WHERE memid='"+memid+"'";
                                    pst = con.prepareStatement(sq);
                                    pst.execute();
                                    JOptionPane.showMessageDialog(null, "Insert succesfull","Information",JOptionPane.INFORMATION_MESSAGE);
                                    clear();
                                    clear2();
                                }
                            }
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }

                    }
                }

            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_insertbtnActionPerformed

    private void gupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gupdatebtnActionPerformed
        String g1name =g1namebox.getText();
        String g1address =g1addressbox.getText();
        String g1nic =g1nicbox.getText();
        String g2name =g2namebox.getText();
        String g2address =g2addressbox.getText();
        String g2nic =g2nicbox.getText();
        String date =datebox.getText();
        String time =timebox.getText();

        if(checkbox.isSelected()){
            if(g1idbox.getText().equals("ID") || g2idbox.getText().equals("ID") || g1name.equals("name") || g1address.equals("address") || g1nic.equals("nic no") || g2name.equals("name") || g2address.equals("address") || g2nic.equals("nic no") || mendabox.getText().isEmpty() || secbox.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Some feilds are Empty","Information",JOptionPane.INFORMATION_MESSAGE);
            }else{
                int amount = Integer.parseInt(amountbox.getText());

                try {
                    pst = con.prepareStatement("SElECT mandatory,securities,interest,loan_limit,toinstallment FROM admin ");
                    rs = pst.executeQuery();
                    rs.next();
                    int manda = rs.getInt("mandatory");
                    int sec = rs.getInt("securities");
                    int interest = rs.getInt("interest");
                    int llimit = rs.getInt("loan_limit");
                    int to = rs.getInt("toinstallment");
                    rs.close();
                    pst = con.prepareStatement("SElECT mendaamount,secamount FROM loan WHERE loanid=?");
                    String sear = loanidbox.getText();
                    pst.setString(1, sear);
                    rs = pst.executeQuery();
                    rs.next();
                    int mandabal = rs.getInt("mendaamount");
                    int secbal =rs.getInt("secamount");
                    rs.close();

                    int valuemanda = amount * manda/100;
                    int valuesec = amount * sec/100;
                    int withinterest = amount * interest/100;
                    int mandaamount = Integer.parseInt(mendabox.getText());
                    int secamount = Integer.parseInt(secbox.getText());
                    int currutmanda = mandabal+mandaamount;
                    int currutsec = secbal+secamount;
                    int redmanda =valuemanda-mandaamount;
                    int redsec =valuesec-secamount;
                    int sum = redmanda+ redsec;
                    int curenntamount = amount+sum+withinterest ;
                    int memid = Integer.parseInt(memidbox.getText());
                    int age = Integer.parseInt(agebox.getText());
                    int intstall = Integer.parseInt(instbox.getText());
                    int g1id = Integer.parseInt(g1idbox.getText());
                    int g2id = Integer.parseInt(g2idbox.getText());

                    if(curenntamount>=llimit+1){

                        JOptionPane.showMessageDialog(null, "Your maximum credit limit has been exceeded");
                    }else{
                        if(intstall>to){
                            JOptionPane.showMessageDialog(null, "Your maximum loan installments have been exceeded");
                        }else{
                            String sql = "UPDATE loan SET age='"+age+"',amount='"+curenntamount+"',installments='"+intstall+"',mendaamount='"+currutmanda+"',secamount='"+currutsec+"',date='"+date+"',time='"+time+"' WHERE memberid='"+memid+"'";
                            pst = con.prepareStatement(sql);
                            pst.execute();

                            String sq = "UPDATE guarantor SET fguarantorid='"+g1id+"',lguarantorid='"+g2id+"',fguarantorname='"+g1name+"',lguarantorname='"+g2name+"',fguarantoradd='"+g1address+"',lguarantoradd='"+g2address+"',fguarantornic='"+g1nic+"',lguarantornic='"+g2nic+"' WHERE memid='"+memid+"'";
                            pst = con.prepareStatement(sq);
                            pst.execute();

                            JOptionPane.showMessageDialog(null, "Update succesfull","Information",JOptionPane.INFORMATION_MESSAGE);
                            clear();
                            clear2();
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }else{
            //  JOptionPane.showMessageDialog(null, "Skkkkkkkkkkkkkk","Information",JOptionPane.INFORMATION_MESSAGE);
            if(g1idbox.getText().equals("ID") || g2idbox.getText().equals("ID") || g1name.equals("name") || g1address.equals("address") || g1nic.equals("nic no") || g2name.equals("name") || g2address.equals("address") || g2nic.equals("nic no")){
                JOptionPane.showMessageDialog(null, "Some feilds are Empty","Information",JOptionPane.INFORMATION_MESSAGE);
            }else{
                try {
                    pst = con.prepareStatement("SElECT mandatory,securities,interest,loan_limit,toinstallment FROM admin ");
                    rs = pst.executeQuery();
                    rs.next();
                    int manda = rs.getInt("mandatory");
                    int sec = rs.getInt("securities");
                    int interest = rs.getInt("interest");
                    int llimit = rs.getInt("loan_limit");
                    int to = rs.getInt("toinstallment");
                    rs.close();
                    int amount = Integer.parseInt(amountbox.getText());
                    int valuemanda = amount * manda/100;
                    int valuesec = amount * sec/100;
                    int withinterest = amount * interest/100;
                    int sum = valuemanda+ valuesec;
                    int curenntamount = amount+sum +withinterest;
                    int mandaamount =0;
                    int secamount =0;
                    int memid = Integer.parseInt(memidbox.getText());
                    int age = Integer.parseInt(agebox.getText());
                    int intstall = Integer.parseInt(instbox.getText());
                    int g1id = Integer.parseInt(g1idbox.getText());
                    int g2id = Integer.parseInt(g2idbox.getText());
                    if(curenntamount>=llimit+1){

                        JOptionPane.showMessageDialog(null, "Your maximum credit limit has been exceeded");
                    }else{
                        if(intstall>to){
                            JOptionPane.showMessageDialog(null, "Your maximum loan installments have been exceeded");
                        }else{
                            String sql = "UPDATE loan SET age='"+age+"',amount='"+curenntamount+"',installments='"+intstall+"',date='"+date+"',time='"+time+"' WHERE memberid='"+memid+"'";
                            pst = con.prepareStatement(sql);
                            pst.execute();

                            String sq = "UPDATE guarantor SET fguarantorid='"+g1id+"',lguarantorid='"+g2id+"',fguarantorname='"+g1name+"',lguarantorname='"+g2name+"',fguarantoradd='"+g1address+"',lguarantoradd='"+g2address+"',fguarantornic='"+g1nic+"',lguarantornic='"+g2nic+"' WHERE memid='"+memid+"'";
                            pst = con.prepareStatement(sq);
                            pst.execute();
                            JOptionPane.showMessageDialog(null, "Update succesfull","Information",JOptionPane.INFORMATION_MESSAGE);
                            clear();
                            clear2();
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

            }
        }
    }//GEN-LAST:event_gupdatebtnActionPerformed

    private void gclearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gclearbtnActionPerformed
        clear2();
    }//GEN-LAST:event_gclearbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        nextpanel.setSelectedIndex(0);
    }//GEN-LAST:event_backbtnActionPerformed

    private void g2findbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g2findbtnActionPerformed
        if(g2searchbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Member ID", "Information", JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(g2searchbox.getText().equals(g1searchbox.getText()) || g2searchbox.getText().equals(g1idbox.getText())){
                JOptionPane.showMessageDialog(null, "He has already appeared as a guarantor", "Information", JOptionPane.INFORMATION_MESSAGE);
            }else{
                if(memidbox.getText().equals(g2searchbox.getText())){
                    JOptionPane.showMessageDialog(null, "He is the borrower", "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    try {
                        int search = Integer.parseInt(g2searchbox.getText());
                        pst = con.prepareStatement("SELECT COUNT(fguarantorid) FROM guarantor WHERE fguarantorid='"+search+"'");
                        rs = pst.executeQuery();
                        rs.next();
                        int cou= rs.getInt("COUNT(fguarantorid)");
                        if(cou<=3){

                            pst = con.prepareStatement("SElECT memberid,fname,lname,address,nicno,phoneno FROM member WHERE memberid='"+search+"'");
                            rs = pst.executeQuery();
                            if(rs.next()==false){
                                JOptionPane.showMessageDialog(null, "Search item not found", "Information", JOptionPane.INFORMATION_MESSAGE);
                            }else{
                                int id =rs.getInt("memberid");
                                String fname = rs.getString("fname");
                                String lname = rs.getString("lname");
                                String address = rs.getString("address");
                                String nic = rs.getString("nicno");
                                String phone = rs.getString("phoneno");

                                g2idbox.setText(String.valueOf(id));
                                g2namebox.setText(fname+" "+lname);
                                g2addressbox.setText(address);
                                g2nicbox.setText(nic);
                                g2searchbox.setText("");
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "He has already appeared as a guarantor for three loans", "Information", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
        }
    }//GEN-LAST:event_g2findbtnActionPerformed

    private void g1findbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g1findbtnActionPerformed
        if(g1searchbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Member ID", "Information", JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(g1searchbox.getText().equals(g2searchbox.getText()) || g1searchbox.getText().equals(g2idbox.getText())){
                JOptionPane.showMessageDialog(null, "He has already appeared as a guarantor", "Information", JOptionPane.INFORMATION_MESSAGE);
            }else{
                if(memidbox.getText().equals(g1searchbox.getText())){
                    JOptionPane.showMessageDialog(null, "He is the borrower", "Information", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    try {
                        int search = Integer.parseInt(g1searchbox.getText());
                        pst = con.prepareStatement("SELECT COUNT(fguarantorid) FROM guarantor WHERE fguarantorid='"+search+"'");
                        rs = pst.executeQuery();
                        rs.next();
                        int cou= rs.getInt("COUNT(fguarantorid)");
                        if(cou<=3){
                            pst = con.prepareStatement("SElECT memberid,fname,lname,address,nicno,phoneno FROM member WHERE memberid='"+search+"'");
                            rs = pst.executeQuery();
                            if(rs.next()==false){
                                JOptionPane.showMessageDialog(null, "Search item not found", "Information", JOptionPane.INFORMATION_MESSAGE);
                            }else{
                                int id =rs.getInt("memberid");
                                String fname = rs.getString("fname");
                                String lname = rs.getString("lname");
                                String address = rs.getString("address");
                                String nic = rs.getString("nicno");
                                String phone = rs.getString("phoneno");

                                g1idbox.setText(String.valueOf(id));
                                g1namebox.setText(fname+" "+lname);
                                g1addressbox.setText(address);
                                g1nicbox.setText(nic);
                                g1searchbox.setText("");
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "He has already appeared as a guarantor for three loans", "Information", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } catch (Exception e) {
                    }
                }
            }
        }
    }//GEN-LAST:event_g1findbtnActionPerformed
    public void checkbox(){
         if(checkbox.isSelected()){
           mendabox.setEditable(true);
           secbox.setEditable(true);
       }else{
             mendabox.setText("");
           mendabox.setEditable(false);
           secbox.setText("");
           secbox.setEditable(false); 
       }
    }
    
    public void clear(){
        memidbox.setText("");
        loanidbox.setText("ID");
        namebox.setText("Name");
        addressbox.setText("Address");
        nicbox.setText("NIC No");
        phonenobox.setText("Phone no");
        agebox.setText("");
        amountbox.setText("");
        instbox.setText("");
        searchbox.setText("");
    }
    
     public void clear2(){
        g1idbox.setText("ID");
        g2idbox.setText("ID");
        g1namebox.setText("name");
        g2namebox.setText("name");
         g1addressbox.setText("address");
         g2addressbox.setText("address");
         g2nicbox.setText("nicno");
         g1nicbox.setText("nicno");
         checkbox.setSelected(false);
        mendabox.setText("");
        secbox.setText("");
    }
    
     public void search(){
         if(searchbox.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Please Enter Member ID or Loan ID");
         }else{
             
             try {
            pst = con.prepareStatement("SElECT memberid,loanid,name,address,phoneno,nic,age,amount,installments,mendaamount,secamount FROM loan WHERE loanid=? or memberid=?");
            String search = searchbox.getText();
            String search2 =searchbox.getText();
            pst.setString(1, search);
            pst.setString(2, search2);
           rs = pst.executeQuery();
           if(rs.next()==false){
               JOptionPane.showMessageDialog(null, "Search item not found");
               clear();
               clear2();
           }else{
            String memid = rs.getString("memberid");
           String loanid = rs.getString("loanid");
           String name = rs.getString("name");
          String address = rs.getString("address");
          String phone = rs.getString("phoneno");
          String nic = rs.getString("nic");
          String age = rs.getString("age");
          String amount = rs.getString("amount");
          String install = rs.getString("installments");
          int manda = rs.getInt("mendaamount");
          String sec = rs.getString("secamount");
          
          memidbox.setText(memid);
        loanidbox.setText( loanid );
        namebox.setText(name);
        addressbox.setText(address);
        nicbox.setText(nic);
        phonenobox.setText(phone);
        agebox.setText(age);
        amountbox.setText(amount);
        instbox.setText(install);
        if (manda==0){
            checkbox.setSelected(false);
            mendabox.setText("");
            secbox.setText("");
        }else{
            checkbox.setSelected(true);
            mendabox.setText(String.valueOf(manda));
            secbox.setText(sec);
        }
        pst = con.prepareStatement("SElECT fguarantorid,lguarantorid,fguarantorname,lguarantorname,fguarantoradd,lguarantoradd,fguarantornic,lguarantornic FROM guarantor WHERE loanid=? or memid=?");
            String searc = searchbox.getText();
            String searc2 =searchbox.getText();
            pst.setString(1, search);
            pst.setString(2, search2);
           rs = pst.executeQuery();
           rs.next();
           String g1id = rs.getString("fguarantorid");
           String g2id = rs.getString("lguarantorid");
           String g1name = rs.getString("fguarantorname");
          String g2name = rs.getString("lguarantorname");
          String g1adress = rs.getString("fguarantoradd");
          String g2address = rs.getString("lguarantoradd");
          String g1nic = rs.getString("fguarantornic");
          String g2nic = rs.getString("lguarantornic");
        
        g1idbox.setText(g1id);
        g2idbox.setText(g2id);
        g1namebox.setText(g1name);
        g2namebox.setText(g2name);
         g1addressbox.setText(g1adress);
         g2addressbox.setText(g2address);
         g2nicbox.setText(g1nic);
         g1nicbox.setText( g2nic);
           }
             } catch (Exception e) {
             }
         }
     }
     
    public void setDateTime() {
        
        Calendar c = Calendar.getInstance();
        hour= c.get(Calendar.HOUR_OF_DAY);
        if (hour >12)
            hour=hour -12;
        minute= c.get(Calendar.MINUTE);
        second= c.get(Calendar.SECOND);
        year= c.get(Calendar.YEAR);
        month= c.get(Calendar.MONTH);
        day= c.get(Calendar.DAY_OF_MONTH);
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date dat = c.getTime();
        timestr=sdf.format(dat);
        yearstr=df.format(dat);
        timebox.setText(timestr);
        datebox.setText(yearstr);
               

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressbox;
    private javax.swing.JTextField agebox;
    private javax.swing.JTextField amountbox;
    private javax.swing.JButton backbtn;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel datebox;
    private javax.swing.JButton findbox;
    private javax.swing.JLabel g1addressbox;
    private javax.swing.JButton g1findbtn;
    private javax.swing.JLabel g1idbox;
    private javax.swing.JLabel g1namebox;
    private javax.swing.JLabel g1nicbox;
    private javax.swing.JTextField g1searchbox;
    private javax.swing.JLabel g2addressbox;
    private javax.swing.JButton g2findbtn;
    private javax.swing.JLabel g2idbox;
    private javax.swing.JLabel g2namebox;
    private javax.swing.JLabel g2nicbox;
    private javax.swing.JTextField g2searchbox;
    private javax.swing.JButton gclearbtn;
    private javax.swing.JButton gupdatebtn;
    private javax.swing.JButton insertbtn;
    private javax.swing.JTextField instbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel loanidbox;
    private javax.swing.JTextField memidbox;
    private javax.swing.JTextField mendabox;
    private javax.swing.JLabel namebox;
    private javax.swing.JButton nextbtn;
    private javax.swing.JTabbedPane nextpanel;
    private javax.swing.JLabel nicbox;
    private javax.swing.JLabel phonenobox;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField secbox;
    private javax.swing.JLabel timebox;
    // End of variables declaration//GEN-END:variables
}
