/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import Code.DBconnect;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author acer
 */
public class membertable extends javax.swing.JInternalFrame {

    String currentDirectory = System.getProperty("user.dir");
    Connection con=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form membertable
     */
    public membertable() {
        initComponents();
        con = DBconnect.connect();
        tableload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        searchbox = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        repotbtn = new javax.swing.JButton();
        printbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        memtable = new javax.swing.JTable();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Member Registration Details");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sanasa2.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(179, 183, 179));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Enter Member ID or Account No  "));
        jPanel3.setLayout(null);

        searchbox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });
        jPanel3.add(searchbox);
        searchbox.setBounds(20, 30, 230, 31);

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel3.add(searchbtn);
        searchbtn.setBounds(260, 30, 90, 30);

        repotbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        repotbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reportb.png"))); // NOI18N
        repotbtn.setText("Report");
        repotbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repotbtnActionPerformed(evt);
            }
        });
        jPanel3.add(repotbtn);
        repotbtn.setBounds(370, 30, 100, 30);

        printbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        printbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/print.png"))); // NOI18N
        printbtn.setText("Print");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        jPanel3.add(printbtn);
        printbtn.setBounds(485, 30, 90, 30);

        memtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(memtable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258))))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        if(searchbox.getText().isEmpty()){
            tableload();

        }

    }//GEN-LAST:event_searchboxKeyReleased

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        if(searchbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Search field is Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            search();
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void repotbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repotbtnActionPerformed
        if(searchbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Member ID", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            print ();
        }

    }//GEN-LAST:event_repotbtnActionPerformed

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        if(searchbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Member ID", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            int id = Integer.parseInt(searchbox.getText());
            if(id>=1 && id<=500){
                try {
                    HashMap m =new HashMap();
                    m.put("memid", searchbox.getText());

                    JasperDesign jdesign = JRXmlLoader.load(currentDirectory + "\\src\\reports\\member.jrxml");
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, m,con);

                    //JasperViewer.viewReport(jprint,false);
                    JasperPrintManager.printReport(jprint, false);
                } catch (JRException ex) {
                    Logger.getLogger(loantable.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "The Member ID can only use number 1 to 500.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_printbtnActionPerformed
public void print (){
       int id = Integer.parseInt(searchbox.getText());
             if(id>=1 && id<=500){
                  try {
            HashMap m =new HashMap();
            m.put("memid", searchbox.getText());
            
            JasperDesign jdesign = JRXmlLoader.load(currentDirectory + "\\src\\reports\\member.jrxml");
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, m,con);
            
            //JasperViewer.viewReport(jprint);
           JasperViewer.viewReport(jprint,false);
            //JasperPrintManager.printReport(jprint, false);
        } catch (JRException ex) {
            Logger.getLogger(loantable.class.getName()).log(Level.SEVERE, null, ex);
        }
             }else{
                 JOptionPane.showMessageDialog(null, "The Member ID can only use number 1 to 500.", "Error", JOptionPane.ERROR_MESSAGE); 
             }
       
    }

private void theader(){
        JTableHeader thead = memtable.getTableHeader();
        thead.setForeground(Color.BLUE);
        
        thead.setFont(new Font("Tahome", Font.BOLD, 12));
    }
    
    public void tableload(){
        try {
            String sql = "SELECT memberid,fname,lname,address,employment,gender,dob,nicno,phoneno,shares,date,time FROM member";
            
            pst =con.prepareStatement(sql);
            rs = pst.executeQuery();
            memtable.setModel(DbUtils.resultSetToTableModel(rs));
            memtable.setBackground(Color.LIGHT_GRAY);
            memtable.setFont(new Font("Times New Roman", Font.BOLD, 13));
            TableColumn col1=memtable.getColumnModel().getColumn(9);
            col1.setPreferredWidth(45);
            TableColumn col2=memtable.getColumnModel().getColumn(5);
            col2.setPreferredWidth(50);
            TableColumn col3=memtable.getColumnModel().getColumn(0);
            col3.setPreferredWidth(60);
            TableColumn col4=memtable.getColumnModel().getColumn(10);
            col4.setPreferredWidth(70);
           theader();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        }

     public void search(){
    
    String srch = searchbox.getText();
        try {
         String sql = "SElECT * FROM member WHERE memberid LIKE '%"+srch+"%'"; 
          pst = con.prepareStatement(sql);
         rs = pst.executeQuery();
         memtable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable memtable;
    private javax.swing.JButton printbtn;
    private javax.swing.JButton repotbtn;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchbtn;
    // End of variables declaration//GEN-END:variables
}
