/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import Code.DBconnect;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author acer
 */
public class naccounttable extends javax.swing.JInternalFrame {

    String currentDirectory = System.getProperty("user.dir");
    Connection con=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form naccounttable
     */
    public naccounttable() {
        initComponents();
       con = DBconnect.connect();
       tableload();
    }
    private void theader(){
        JTableHeader thead = nacctable.getTableHeader();
        thead.setForeground(Color.BLUE);
        
        thead.setFont(new Font("Tahome", Font.BOLD, 12));
    }
    public void tableload(){
        try {
            String sql = "SELECT * FROM nonmemberacc";
            
            pst =con.prepareStatement(sql);
            rs = pst.executeQuery();
            nacctable.setModel(DbUtils.resultSetToTableModel(rs));
            nacctable.setBackground(Color.LIGHT_GRAY);
            nacctable.setFont(new Font("Times New Roman", Font.BOLD, 13));
           theader();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        }
    
    public void search(){
    
    String srch = searchbox.getText();
        try {
         String sql = "SElECT * FROM nonmemberacc WHERE accno='"+srch+"'"; 
          pst = con.prepareStatement(sql);
         rs = pst.executeQuery();
         nacctable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        }
    
    }
    
    public void print (){
        int id = Integer.parseInt(searchbox.getText());
             if(id>=701){
                        try {
            HashMap m =new HashMap();
            m.put("accno", searchbox.getText());
            
            JasperDesign jdesign = JRXmlLoader.load(currentDirectory + "\\src\\reports\\nonmemberacc.jrxml");
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, m,con);
            
            //JasperViewer.viewReport(jprint);
           JasperViewer.viewReport(jprint,false);
            //JasperPrintManager.printReport(jprint, false);
        } catch (JRException ex) {
            Logger.getLogger(loantable.class.getName()).log(Level.SEVERE, null, ex);
        } 
             }else{
                 JOptionPane.showMessageDialog(null, "The Non-member ID can only used on numbers above 700.", "Error", JOptionPane.ERROR_MESSAGE); 
             }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        searchbox = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        reportbtn = new javax.swing.JButton();
        printbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nacctable = new javax.swing.JTable();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Non-member Account Details");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sanasa2.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(179, 183, 179));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Enter Account No"));
        jPanel3.setLayout(null);

        searchbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchboxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });
        jPanel3.add(searchbox);
        searchbox.setBounds(20, 30, 150, 30);

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel3.add(searchbtn);
        searchbtn.setBounds(190, 30, 90, 30);

        reportbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reportbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reportb.png"))); // NOI18N
        reportbtn.setText("Report");
        reportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbtnActionPerformed(evt);
            }
        });
        jPanel3.add(reportbtn);
        reportbtn.setBounds(300, 30, 100, 30);

        printbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        printbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/print.png"))); // NOI18N
        printbtn.setText("Print");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        jPanel3.add(printbtn);
        printbtn.setBounds(410, 30, 90, 30);

        nacctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(nacctable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(212, 212, 212))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        if(searchbox.getText().isEmpty()){
            tableload();

        }
    }//GEN-LAST:event_searchboxKeyReleased

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        if(searchbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Search field is Empty", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            search();
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtnActionPerformed
        if(searchbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Account Number", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            print ();
        }
    }//GEN-LAST:event_reportbtnActionPerformed

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        if(searchbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Account Number", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            int id = Integer.parseInt(searchbox.getText());
            if(id>=701){
                try {
                    HashMap m =new HashMap();
                    m.put("accno", searchbox.getText());

                    JasperDesign jdesign = JRXmlLoader.load(currentDirectory + "\\src\\reports\\nonmemberacc.jrxml");
                    JasperReport jreport = JasperCompileManager.compileReport(jdesign);
                    JasperPrint jprint = JasperFillManager.fillReport(jreport, m,con);

                    //JasperViewer.viewReport(jprint,false);
                    JasperPrintManager.printReport(jprint, false);
                } catch (JRException ex) {
                    Logger.getLogger(loantable.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "The Non-member ID can only used on numbers above 700.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_printbtnActionPerformed

    private void searchboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyPressed
        String   phone =searchbox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<3){
                searchbox.setEditable(true);
            }else{
                searchbox.setEditable(false);
            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                searchbox.setEditable(true);
            }else{
                searchbox.setEditable(false);
            }
        }
    }//GEN-LAST:event_searchboxKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable nacctable;
    private javax.swing.JButton printbtn;
    private javax.swing.JButton reportbtn;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchbtn;
    // End of variables declaration//GEN-END:variables
}
