/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import Code.DBconnect;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author acer
 */
public class nonmember extends javax.swing.JInternalFrame {

    Connection con=null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int hour,second,minute;
    int day,month,year;
    String timestr,yearstr;
    /**
     * Creates new form nonmember
     */
    public nonmember() {
        initComponents();
        con = DBconnect.connect();
        autoID();
        ((JTextField)datechooser.getDateEditor().getUiComponent()).setText("dd/MM/yyyy");
        setDateTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        datechooser = new com.toedter.calendar.JDateChooser();
        empbox = new javax.swing.JTextField();
        phonenobox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nonidbox = new javax.swing.JTextField();
        fnamebox = new javax.swing.JTextField();
        lnamebox = new javax.swing.JTextField();
        addressbox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sonamebox = new javax.swing.JTextField();
        soaddressbox = new javax.swing.JTextField();
        nicbox = new javax.swing.JTextField();
        relationbox = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        searchbox = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        ndatebox = new javax.swing.JLabel();
        ntimebox = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(763, 620));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        datechooser.setDateFormatString("dd/MM/yyyy");

        empbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        phonenobox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        phonenobox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonenoboxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phonenoboxKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Employment");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Phone No");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date Of Birth");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Non-Member ID");

        nonidbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nonidbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nonidboxKeyPressed(evt);
            }
        });

        fnamebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        lnamebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        addressbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addressbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressboxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Non-member");

        sonamebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sonamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonameboxActionPerformed(evt);
            }
        });

        soaddressbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        soaddressbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soaddressboxActionPerformed(evt);
            }
        });

        nicbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        relationbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Relationship");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("NIC No");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Address");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Name");

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("Subsequent owner details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sonamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nicbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(relationbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(soaddressbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sonamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soaddressbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relationbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(14, 14, 14))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Enter Non-Member ID"));
        jPanel5.setLayout(null);

        searchbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchboxKeyPressed(evt);
            }
        });
        jPanel5.add(searchbox);
        searchbox.setBounds(10, 30, 210, 30);

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbtnMouseClicked(evt);
            }
        });
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel5.add(searchbtn);
        searchbtn.setBounds(230, 30, 72, 30);

        addbtn.setBackground(new java.awt.Color(204, 204, 204));
        addbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addbtn.setText("ADD");
        addbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        updatebtn.setBackground(new java.awt.Color(204, 204, 204));
        updatebtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebtnMouseClicked(evt);
            }
        });
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(204, 204, 204));
        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deletebtn.setText("Delete");
        deletebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        clearbtn.setBackground(new java.awt.Color(204, 204, 204));
        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        ndatebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ndatebox.setText("Date");

        ntimebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ntimebox.setText("Time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addComponent(ndatebox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ntimebox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nonidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressbox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datechooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phonenobox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empbox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nonidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(fnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(addressbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(phonenobox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(empbox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ndatebox)
                            .addComponent(ntimebox))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phonenoboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenoboxKeyPressed
        String   phone =phonenobox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<10){
                phonenobox.setEditable(true);
            }else{
                phonenobox.setEditable(false);
            }
        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                phonenobox.setEditable(true);
            }else{
                phonenobox.setEditable(false);
            }
        }
    }//GEN-LAST:event_phonenoboxKeyPressed

    private void phonenoboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenoboxKeyReleased
        phoneno();
    }//GEN-LAST:event_phonenoboxKeyReleased

    private void nonidboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nonidboxKeyPressed
        String   phone =nonidbox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<3){
                nonidbox.setEditable(true);
            }else{
                nonidbox.setEditable(false);

            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                nonidbox.setEditable(true);
            }else{
                nonidbox.setEditable(false);
            }
        }
    }//GEN-LAST:event_nonidboxKeyPressed

    private void addressboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressboxActionPerformed

    private void sonameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonameboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sonameboxActionPerformed

    private void soaddressboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soaddressboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soaddressboxActionPerformed

    private void searchboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyPressed
        String phone =searchbox.getText();
        int length = phone.length();
        char c = evt.getKeyChar();

        if ( evt.getKeyChar()>='0' &&  evt.getKeyChar()<='9'){
            if (length<3){
                searchbox.setEditable(true);
            }else{
                searchbox.setEditable(false);

            }

        }else{
            if (evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE){
                searchbox.setEditable(true);
            }else{
                searchbox.setEditable(false);
            }
        }
    }//GEN-LAST:event_searchboxKeyPressed

    private void searchbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbtnMouseClicked
        phoneno();
    }//GEN-LAST:event_searchbtnMouseClicked

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed

        if(searchbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Non-Member ID","Information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                pst = con.prepareStatement("SElECT nonmemid,fname,lname,address,dob,phoneno,employment,soname,soaddress,sonicno,relationship FROM nonmember WHERE nonmemid=?");
                int search = Integer.parseInt(searchbox.getText());
                pst.setInt(1, search);
                rs = pst.executeQuery();

                if(rs.next()==false){
                    JOptionPane.showMessageDialog(null, "Search item not found","Information",JOptionPane.INFORMATION_MESSAGE);
                }else{
                    String id = rs.getString("nonmemid");
                    String fname =  rs.getString("fname");
                    String lname =  rs.getString("lname");
                    String nic =  rs.getString("sonicno");
                    String address =  rs.getString("address");
                    String date = rs.getString("dob");
                    String emp =  rs.getString("employment");
                    String soname =  rs.getString("soname");
                    String soaddress =  rs.getString("soaddress");
                    String phoneno =  rs.getString("phoneno");
                    String relation =  rs.getString("relationship");

                    ((JTextField)datechooser.getDateEditor().getUiComponent()).setText(date);
                    nonidbox.setText(id);
                    fnamebox.setText(fname);
                    lnamebox.setText(lname);
                    nicbox.setText(nic);
                    addressbox.setText(address);
                    empbox.setText(emp);
                    sonamebox.setText(soname);
                    soaddressbox.setText(soaddress);
                    phonenobox.setText(phoneno);
                    relationbox.setText(relation);

                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
        Date date;
        date = datechooser.getDate();
        try {
            String s =((JTextField)datechooser.getDateEditor().getUiComponent()).getText();

            if (s.equals("dd/MM/yyyy")){
                JOptionPane.showMessageDialog(null,"Please Enter Birthday", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_addbtnMouseClicked

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        SimpleDateFormat dformat = new SimpleDateFormat("dd/MM/yyyy");
        String dob =dformat.format(datechooser.getDate());

        String phoneno;
        String fname;
        String lname;
        String address;
        String soaddress;
        String soname;
        String relation;
        int nonmemid;
        String nic;
        String date;
        String time;
        String emp;

        phoneno = phonenobox.getText();
        fname = fnamebox.getText();
        lname = lnamebox.getText();
        address = addressbox.getText();
        nonmemid=Integer.parseInt(nonidbox.getText());
        nic = nicbox.getText();
        date = ndatebox.getText();
        time= ntimebox.getText();
        emp = empbox.getText();
        soaddress= soaddressbox.getText();
        soname= sonamebox.getText();
        relation= relationbox.getText();

        try {
            pst= con.prepareStatement("SELECT nonmemid FROM nonmember WHERE nonmemid='"+nonmemid+"'");
            rs=pst.executeQuery();
            if(rs.next()==true){
                JOptionPane.showMessageDialog(null, "Already Registered");
            }else{

                if(phoneno.isEmpty() || fname.isEmpty() || lname.isEmpty() || address.isEmpty() || nonidbox.getText().isEmpty() || soaddress.isEmpty() || nic.isEmpty() || date.isEmpty() || time.isEmpty() || emp.isEmpty() || soname.isEmpty() || relation.isEmpty()){

                    JOptionPane.showMessageDialog(null, "Some fields are Empty");
                }else{
                    pst = con.prepareStatement("SElECT accno FROM deaccount WHERE accno=?");
                    pst.setInt(1, nonmemid);
                    rs = pst.executeQuery();
                    if (rs.next()==true){

                        String sq = "DELETE FROM deaccount WHERE accno='"+nonmemid+"'";
                        pst = con.prepareStatement(sq);
                        pst.execute();

                        String sql = "INSERT INTO nonmember (nonmemid,fname,lname,address,dob,phoneno,employment,soname,soaddress,sonicno,relationship,date,time) VALUES ('"+nonmemid+"','"+fname+"', '"+lname+"','"+address+"','"+dob+"','"+phoneno+"','"+emp+"', '"+soname+"','"+soaddress+"','"+nic+"','"+relation+"','"+date+"','"+time+"')";
                        pst = con.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null,"Added Succesfull","Information",JOptionPane.INFORMATION_MESSAGE);
                        autoID();
                        clear();
                    }else{
                        String sql = "INSERT INTO nonmember (nonmemid,fname,lname,address,dob,phoneno,employment,soname,soaddress,sonicno,relationship,date,time) VALUES ('"+nonmemid+"','"+fname+"', '"+lname+"','"+address+"','"+dob+"','"+phoneno+"','"+emp+"', '"+soname+"','"+soaddress+"','"+nic+"','"+relation+"','"+date+"','"+time+"')";
                        pst = con.prepareStatement(sql);
                        pst.execute();
                        JOptionPane.showMessageDialog(null,"Added Succesfull","Information",JOptionPane.INFORMATION_MESSAGE);
                        autoID();
                        clear();
                    }

                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void updatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseClicked
        Date date;
        date = datechooser.getDate();
        try {
            String s =((JTextField)datechooser.getDateEditor().getUiComponent()).getText();

            if (s.equals("dd/MM/yyyy")){
                JOptionPane.showMessageDialog(null,"Please Enter Birthday", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_updatebtnMouseClicked

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        SimpleDateFormat dformat = new SimpleDateFormat("dd/MM/yyyy");
        String dob =dformat.format(datechooser.getDate());

        String phoneno;
        String fname;
        String lname;
        String address;
        String soaddress;
        String soname;
        String relation;
        int nonmemid;
        String nic;
        String date;
        String time;
        String emp;

        phoneno = phonenobox.getText();
        fname = fnamebox.getText();
        lname = lnamebox.getText();
        address = addressbox.getText();
        nonmemid=Integer.parseInt(nonidbox.getText());
        nic = nicbox.getText();
        date = ndatebox.getText();
        time= ntimebox.getText();
        emp = empbox.getText();
        soaddress= soaddressbox.getText();
        soname= sonamebox.getText();
        relation= relationbox.getText();

        if(phoneno.isEmpty() || fname.isEmpty() || lname.isEmpty() || address.isEmpty() || nonidbox.getText().isEmpty() || soaddress.isEmpty() || nic.isEmpty() || date.isEmpty() || time.isEmpty() || emp.isEmpty() || soname.isEmpty() || relation.isEmpty()){
            JOptionPane.showMessageDialog(null, "Some fields are Empty");
        }else{
            try {
                String sq = "UPDATE nonmember SET fname='"+fname+"',lname='"+lname+"',address='"+address+"',dob='"+dob+"',phoneno='"+phoneno+"',employment='"+emp+"',soname='"+soname+"',soaddress='"+soaddress+"',sonicno='"+nic+"',relationship='"+relation+"'  WHERE nonmemid= '"+nonmemid+"'";
                pst = con.prepareStatement(sq);
                pst.execute();
                JOptionPane.showMessageDialog(null,"Updated Succesfull ");
                clear();
                autoID();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        String name;
        int nonmemid;
        String date;
        String time;

        name = fnamebox.getText() +" " + lnamebox.getText();
        nonmemid=Integer.parseInt(nonidbox.getText());
        date = ndatebox.getText();
        time= ntimebox.getText();

        int check= JOptionPane.showConfirmDialog(null, "Do You Want to Delete?");
        if(check==0){
            try {
                String sql = "INSERT INTO deaccount (accno,name,date,time) VALUES ('"+nonmemid+"','"+name+"','"+date+"','"+time+"')";
                pst = con.prepareStatement(sql);
                pst.execute();

                String bal ="SELECT balance FROM nonmemberacc WHERE nonmemid='"+nonmemid+"' " ;
                pst = con.prepareStatement(bal);
                rs = pst.executeQuery();
                if(rs.next()==false){
                    int balance = 0;
                    String type= "Non-Member";
                    int amount =0;
                }else{
                    // int amount= rs.getInt("balance");
                    String type= "Non-Member";
                    int balance= rs.getInt("balance");
                    String with = "INSERT INTO withdraw (accno,name,amount,balance,acc_type,date,time) VALUES ('"+nonmemid+"','"+name+"','"+balance+"','"+balance+"','"+type+"','"+date+"','"+time+"')";
                    pst = con.prepareStatement(with);
                    pst.execute();
                }

                String sq = "DELETE FROM nonmember WHERE nonmemid='"+nonmemid+"'";
                pst = con.prepareStatement(sq);
                pst.execute();

                String s = "DELETE FROM nonmemberacc WHERE accno='"+nonmemid+"'";
                pst = con.prepareStatement(s);
                pst.execute();

                JOptionPane.showMessageDialog(null,"Deleted Succesfull ");
            } catch (Exception e) {
            }
        }
        clear();
        autoID();
    }//GEN-LAST:event_deletebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clear();
        autoID();
    }//GEN-LAST:event_clearbtnActionPerformed
    public void phoneno(){
         String   phone =phonenobox.getText();
        int length = phone.length();
        if(phone.isEmpty()){
           phonenobox.setBackground(Color.WHITE);
        }else{
            if(length<10){
                addbtn.setEnabled(false);
              phonenobox.setBackground(Color.RED);
              updatebtn.setEnabled(false);
            }else{
                if(length==10){
                    addbtn.setEnabled(true);
                    updatebtn.setEnabled(true);
                   phonenobox.setBackground(Color.GREEN);
                }else{
                    addbtn.setEnabled(false);
                    updatebtn.setEnabled(false);
                }
            }
        }
    }
    
    public void clear(){
        fnamebox.setText("");
        lnamebox.setText("");
        addressbox.setText("");
        empbox.setText("");
        nicbox.setText("");
        phonenobox.setText("");
        ((JTextField)datechooser.getDateEditor().getUiComponent()).setText("dd/MM/yyyy");
        searchbox.setText("");
        soaddressbox.setText("");
        sonamebox.setText("");
        relationbox.setText("");
    }
    
     public void autoID(){
       try{
       String sql ="SELECT max(nonmemid)+1 FROM nonmember " ;
       pst = con.prepareStatement(sql);
       rs = pst.executeQuery();
       rs.next();
        if ( rs.getString("max(nonmemid)+1")==null){
     
       nonidbox.setText("701");
     }else{
        String max=rs.getString("max(nonmemid)+1");
        nonidbox.setText(max);
        }
    
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
       }
        
}
     
      public void setDateTime() {
        
        Calendar c = Calendar.getInstance();
        hour= c.get(Calendar.HOUR_OF_DAY);
        if (hour >12)
            hour=hour -12;
        minute= c.get(Calendar.MINUTE);
        second= c.get(Calendar.SECOND);
        year= c.get(Calendar.YEAR);
        month= c.get(Calendar.MONTH);
        day= c.get(Calendar.DAY_OF_MONTH);
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date dat = c.getTime();
        timestr=sdf.format(dat);
        yearstr=df.format(dat);
        ntimebox.setText(timestr);
        ndatebox.setText(yearstr);
               

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField addressbox;
    private javax.swing.JButton clearbtn;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField empbox;
    private javax.swing.JTextField fnamebox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField lnamebox;
    private javax.swing.JLabel ndatebox;
    private javax.swing.JTextField nicbox;
    private javax.swing.JTextField nonidbox;
    private javax.swing.JLabel ntimebox;
    private javax.swing.JTextField phonenobox;
    private javax.swing.JTextField relationbox;
    private javax.swing.JTextField searchbox;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField soaddressbox;
    private javax.swing.JTextField sonamebox;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
