/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interface;

import Code.DBconnect;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class withdraw extends javax.swing.JInternalFrame {

    Connection con=null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    int hour,second,minute;
    int day,month,year;
    String timestr,yearstr;
    /**
     * Creates new form withdraw
     */
    public withdraw() {
        initComponents();
        con = DBconnect.connect();
        txtarea.setEditable(false);
        setDateTime();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        findbox = new javax.swing.JTextField();
        findbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idbox = new javax.swing.JLabel();
        namebox = new javax.swing.JLabel();
        typebox = new javax.swing.JLabel();
        amountbox = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        withdrawbox = new javax.swing.JTextField();
        withdrawbtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        printbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        datebox = new javax.swing.JLabel();
        timebox = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Withdraw");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sanasa2.png"))); // NOI18N

        jPanel3.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(null);

        jPanel4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Please Enter Account No"));
        jPanel4.setLayout(null);

        findbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        findbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findboxActionPerformed(evt);
            }
        });
        jPanel4.add(findbox);
        findbox.setBounds(40, 30, 230, 30);

        findbtn.setBackground(new java.awt.Color(204, 204, 204));
        findbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        findbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_icon.png"))); // NOI18N
        findbtn.setText("Find");
        findbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findbtnActionPerformed(evt);
            }
        });
        jPanel4.add(findbtn);
        findbtn.setBounds(200, 70, 80, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(20, 11, 310, 110);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ID");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 140, 30, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Full Name");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 190, 110, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Account type");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 230, 110, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Current Amount");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 280, 110, 15);

        idbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        idbox.setText("ID");
        jPanel3.add(idbox);
        idbox.setBounds(160, 140, 50, 20);

        namebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        namebox.setText("Name");
        jPanel3.add(namebox);
        namebox.setBounds(160, 190, 140, 14);

        typebox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        typebox.setText("Acc Type");
        jPanel3.add(typebox);
        typebox.setBounds(160, 230, 130, 14);

        amountbox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        amountbox.setText("Amount");
        jPanel3.add(amountbox);
        amountbox.setBounds(160, 280, 70, 14);

        jPanel5.setBackground(javax.swing.UIManager.getDefaults().getColor("Component.focusColor"));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.setLayout(null);

        withdrawbox.setBackground(new java.awt.Color(255, 93, 76));
        withdrawbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        withdrawbox.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(withdrawbox);
        withdrawbox.setBounds(80, 30, 122, 43);

        withdrawbtn.setBackground(new java.awt.Color(204, 204, 204));
        withdrawbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        withdrawbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/withdraw.png"))); // NOI18N
        withdrawbtn.setText("Withdraw");
        withdrawbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdrawbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawbtnActionPerformed(evt);
            }
        });
        jPanel5.add(withdrawbtn);
        withdrawbtn.setBounds(50, 110, 130, 40);

        clearbtn.setBackground(new java.awt.Color(204, 204, 204));
        clearbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clean.png"))); // NOI18N
        clearbtn.setText("Clear");
        clearbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        jPanel5.add(clearbtn);
        clearbtn.setBounds(50, 170, 130, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setText("Rs");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(30, 30, 50, 50);

        printbtn.setBackground(new java.awt.Color(204, 204, 204));
        printbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/print.png"))); // NOI18N
        printbtn.setText("Print");
        printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printbtnActionPerformed(evt);
            }
        });
        jPanel5.add(printbtn);
        printbtn.setBounds(50, 230, 130, 40);

        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtarea.setRows(5);
        txtarea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(txtarea);

        datebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        datebox.setText("Date");

        timebox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        timebox.setText("Time");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(datebox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timebox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2)
                            .addGap(312, 312, 312)
                            .addComponent(jLabel1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                .addGap(32, 32, 32)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datebox)
                            .addComponent(timebox))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findboxActionPerformed

    private void findbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findbtnActionPerformed
        if(findbox.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Account Number");
        }else{
            int search = Integer.parseInt(findbox.getText());
            if(search>=1 && search<=500){
                try {
                    pst = con.prepareStatement("SELECT memberid,fname,lname FROM member WHERE memberid = ?");
                    pst.setInt(1, search);
                    rs = pst.executeQuery();
                    if(rs.next()==false){
                        JOptionPane.showMessageDialog(null, "Search item not found","Information",JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        String fname =  rs.getString("fname");
                        String lname =  rs.getString("lname");
                        String id =  rs.getString("memberid");

                        namebox.setText(fname+" "+lname);
                        idbox.setText(id);
                        typebox.setText("Member");

                        pst = con.prepareStatement("SELECT balance FROM memberacc WHERE accno = ?");
                        pst.setInt(1, search);
                        rs = pst.executeQuery();
                        if(rs.next()==false){
                            JOptionPane.showMessageDialog(null, "Search item not found","Information",JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            String balance =  rs.getString("balance");
                            amountbox.setText(balance);
                        }
                    }

                } catch (Exception e) {
                }
            }else{
                if(search>=501 && search<=700){
                    try {
                        pst = con.prepareStatement("SELECT childid,fname,lname FROM child WHERE childid = ?");
                        pst.setInt(1, search);
                        rs = pst.executeQuery();
                        if(rs.next()==false){
                            JOptionPane.showMessageDialog(null, "Search item not found","Information",JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            String fname =  rs.getString("fname");
                            String lname =  rs.getString("lname");
                            String id =  rs.getString("childid");

                            namebox.setText(fname+" "+lname);
                            idbox.setText(id);
                            typebox.setText("Child");

                            pst = con.prepareStatement("SELECT balance FROM childacc WHERE accno = ?");
                            pst.setInt(1, search);
                            rs = pst.executeQuery();
                            if(rs.next()==false){
                                JOptionPane.showMessageDialog(null, "Search item not found","Information",JOptionPane.INFORMATION_MESSAGE);
                            }else{
                                String balance =  rs.getString("balance");
                                amountbox.setText(balance);
                            }
                        }
                    } catch (Exception e) {
                    }

                }else{
                    try {
                        pst = con.prepareStatement("SELECT nonmemid,fname,lname FROM nonmember WHERE nonmemid = ?");
                        pst.setInt(1, search);
                        rs = pst.executeQuery();
                        if(rs.next()==false){
                            JOptionPane.showMessageDialog(null, "Search item not found","Information",JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            String fname =  rs.getString("fname");
                            String lname =  rs.getString("lname");
                            String id =  rs.getString("nonmemid");

                            namebox.setText(fname+" "+lname);
                            idbox.setText(id);
                            typebox.setText("Non-Member");

                            pst = con.prepareStatement("SELECT balance FROM nonmemberacc WHERE accno = ?");
                            pst.setInt(1, search);
                            rs = pst.executeQuery();
                            if(rs.next()==true){
                                String balance =  rs.getString("balance");
                                amountbox.setText(balance);
                            }else{
                                JOptionPane.showMessageDialog(null, "Search item not found","Information",JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                    } catch (Exception e) {
                    }
                }
            }
        }
        findbox.setText("");
    }//GEN-LAST:event_findbtnActionPerformed

    private void withdrawbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawbtnActionPerformed
        if(withdrawbox.getText().isEmpty() || idbox.getText().equals("ID") || namebox.getText().equals("Name") || typebox.getText().equals("Acc Type") || amountbox.getText().equals("Amount")){
            JOptionPane.showMessageDialog(null, "Some feild is Empty","Information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            int amount = Integer.parseInt(amountbox.getText());
            int withdraw = Integer.parseInt(withdrawbox.getText());
            if((amount-500)<=withdraw){
                JOptionPane.showMessageDialog(null, "Your account balance is not sufficient to complete your transaction ","Information",JOptionPane.INFORMATION_MESSAGE);
            }else{
                String time;
                String date;
                int accno;
                String name;
                String type;

                date = datebox.getText();
                time = timebox.getText();
                name = namebox.getText();
                type = typebox.getText();
                accno =  Integer.parseInt(idbox.getText());

                try {
                    int sum = Integer.parseInt(amountbox.getText()) - Integer.parseInt(withdrawbox.getText());
                    String sum1 = String.valueOf(sum);
                    String sql = "INSERT INTO withdraw (accno,name,amount,balance,acc_type,date,time) VALUES ('"+accno+"','"+name+"','"+withdraw+"','"+sum1+"','"+type+"','"+date+"','"+time+"')";
                    pst = con.prepareStatement(sql);
                    pst.execute();
                    if(accno>=1 && accno<=500){
                        String sq = "UPDATE memberacc SET balance='"+sum1+"' WHERE accno= '"+accno+"'";
                        pst = con.prepareStatement(sq);
                        pst.execute();
                        JOptionPane.showMessageDialog(null,"Withdraw Succesfull");
                    }else{
                        if(accno>=501 && accno<=700){
                            String sq = "UPDATE childacc SET balance='"+sum1+"' WHERE accno= '"+accno+"'";
                            pst = con.prepareStatement(sq);
                            pst.execute();
                            JOptionPane.showMessageDialog(null,"Withdraw Succesfull");
                        }else{
                            String sq = "UPDATE nonmemberacc SET balance='"+sum1+"' WHERE accno= '"+accno+"'";
                            pst = con.prepareStatement(sq);
                            pst.execute();
                            JOptionPane.showMessageDialog(null,"Withdraw Succesfull");
                        }
                    }

                } catch (Exception e) {
                }
                print();
                clear();
            }
        }
    }//GEN-LAST:event_withdrawbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        clear();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void printbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printbtnActionPerformed
        if(txtarea.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Bill area is Empty","Information",JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                txtarea.print();
            } catch (PrinterException ex) {
                Logger.getLogger(withdraw.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtarea.setText("");
    }//GEN-LAST:event_printbtnActionPerformed

    public void clear(){
        findbox.setText("");
        idbox.setText("ID");
        namebox.setText("Name");
        typebox.setText("Acc Type");
        withdrawbox.setText("");
        amountbox.setText("Amount");
    }
    public void print(){
         String time = timebox.getText();;
           String date =datebox.getText() ;
           int accno = Integer.parseInt(idbox.getText());
           String name =namebox.getText();
           String type =typebox.getText();
           int withdraw =Integer.parseInt(withdrawbox.getText());
       int sum = Integer.parseInt(amountbox.getText()) - withdraw;
       
       txtarea.setText(txtarea.getText()+"      "+"       SANASA BANK \n");
       txtarea.setText(txtarea.getText()+" \n");
       txtarea.setText(txtarea.getText()+"     "+"Date"+"\t"+"\t"+"Time");
       txtarea.setText(txtarea.getText()+"\n");
      txtarea.setText(txtarea.getText()+"     "+date+"         "+time);
        txtarea.setText(txtarea.getText()+"\n");
       txtarea.setText(txtarea.getText()+" \n");
       txtarea.setText(txtarea.getText()+"     "+"Account No     :  "+accno+"\n");
       txtarea.setText(txtarea.getText()+"\n");
       txtarea.setText(txtarea.getText()+"     "+"Name           :  "+name+"\n");
       txtarea.setText(txtarea.getText()+"\n");
       txtarea.setText(txtarea.getText()+"     "+"Account type   :  "+type+"\n");
       txtarea.setText(txtarea.getText()+"\n");
       txtarea.setText(txtarea.getText()+"     "+"Withdrawal     :  Rs."+withdraw+".00/="+"\n");
       txtarea.setText(txtarea.getText()+"\n");
       txtarea.setText(txtarea.getText()+"     "+"Ledger Balance :  Rs."+sum+".00/="+"\n");
       txtarea.setText(txtarea.getText()+"\n");
       txtarea.setText(txtarea.getText()+"\n");
       txtarea.setText(txtarea.getText()+"     "+"      Thank You come again \n");
     }
    
    public void setDateTime() {
        
        Calendar c = Calendar.getInstance();
        hour= c.get(Calendar.HOUR_OF_DAY);
        if (hour >12)
            hour=hour -12;
        minute= c.get(Calendar.MINUTE);
        second= c.get(Calendar.SECOND);
        year= c.get(Calendar.YEAR);
        month= c.get(Calendar.MONTH);
        day= c.get(Calendar.DAY_OF_MONTH);
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date dat = c.getTime();
        timestr=sdf.format(dat);
        yearstr=df.format(dat);
        timebox.setText(timestr);
        datebox.setText(yearstr);
               
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountbox;
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel datebox;
    private javax.swing.JTextField findbox;
    private javax.swing.JButton findbtn;
    private javax.swing.JLabel idbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namebox;
    private javax.swing.JButton printbtn;
    private javax.swing.JLabel timebox;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JLabel typebox;
    private javax.swing.JTextField withdrawbox;
    private javax.swing.JButton withdrawbtn;
    // End of variables declaration//GEN-END:variables
}
